test names in conference_test
TokTok/c-toxcore pull request #1031
Opened 2018-07-25 10:12 UTC by zugz

2018-07-25 10:12 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/TokTok/c-toxcore?pullRequest=1031) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/TokTok/c-toxcore?pullRequest=1031) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/TokTok/c-toxcore?pullRequest=1031) it.</sub>

2018-07-28 16:41 UTC, iphydf requested changes

2018-07-28 16:41 UTC, iphydf commented on auto_tests/conference_test.c
> +            const int len = tox_conference_peer_get_name_size(toxes[i], 0, j, nullptr);
size_t or uint32_t

2018-07-28 16:41 UTC, iphydf commented on auto_tests/conference_test.c
> +        char name[NAMELEN+1];
Add more spaces (maybe run format-source?).

2018-07-31 21:15 UTC, zugz commented
Closing in favour of #1035

2018-07-31 21:15 UTC, closed without merging