Add AUTOTEST Option to CMakeList.txt
TokTok/c-toxcore pull request #1223
Opened 2018-10-06 18:04 UTC by chron0

2018-10-06 18:04 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/TokTok/c-toxcore?pullRequest=1223) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/TokTok/c-toxcore?pullRequest=1223) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/TokTok/c-toxcore?pullRequest=1223) it.</sub>

2018-10-06 20:48 UTC, iphydf requested changes

2018-10-06 20:48 UTC, iphydf commented on CMakeLists.txt
> +  add_library(misc_tools
misc_tools is needed for other things than auto tests. Better add the condition to the existing `if` inside `function(auto_test target)`.

2018-10-06 20:58 UTC, iphydf requested changes

2018-10-06 20:58 UTC, iphydf commented on CMakeLists.txt
> +    # We need to compile cpufeatures.c as many times as there are executables,
Undo indentation.

2018-10-06 20:58 UTC, iphydf commented on CMakeLists.txt
> +if(AUTOTEST)
Why not add the condition inside the existing `if`?

2018-10-06 22:43 UTC, iphydf commented
Can you update README.md with the new option?

2018-10-07 00:35 UTC, iphydf approved these changes

2018-10-07 15:33 UTC, nurupo requested changes
Also enable autotests in https://github.com/TokTok/c-toxcore/blob/master/.travis/cmake-freebsd-stage2#L53

2018-10-07 15:33 UTC, nurupo commented on CMakeLists.txt
> +option(AUTOTEST "Enable Testing" OFF)
Would be nice if the description matched the one from INSTALL.md

2018-10-07 19:23 UTC, nurupo approved these changes

2018-10-07 22:50 UTC, merged