New Handshake based on Noise IK pattern
TokTok/c-toxcore pull request #1561
Opened 2020-05-14 12:17 UTC by goldroom

New Handshake based on Noise IK pattern

2020-05-14 12:17 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/TokTok/c-toxcore?pullRequest=1561) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/TokTok/c-toxcore?pullRequest=1561) before we can accept your contribution.<br/><hr/>**tb** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/TokTok/c-toxcore?pullRequest=1561) it.</sub>

2021-01-13 09:31 UTC, gjedeer commented
This will be a backwards-incompatible change, yes? I have a backwards-incompatible change coming up in tuntox and would like to schedule it at the same time to minimize the chaos.

2021-01-13 10:46 UTC, zoff99 commented
@gjedeer yes how it looks now it will not be compatible with current toxcore. also NGC (new group chats) will be a breaking change.
we do not yet have an exact date when these 2 will be merged into master.

2021-12-02 21:25 UTC, iphydf requested changes
This code needs a bit of cleanup and testing. Can you fix the CI builds? We'll need to install the noise library there and find it with cmake. I'll take care of the bazel build once that's done.

2021-12-02 21:25 UTC, iphydf commented on CMakeLists.txt
> +set(toxcore_LINK_MODULES ${toxcore_LINK_MODULES} ${LIBSODIUM_LIBRARIES} "/usr/local/lib/libnoiseprotocol.a")
We'll need to search for the library instead of hard-coding it here.

2021-12-02 21:25 UTC, iphydf commented on toxcore/net_crypto.c
> +    //AKE NEW: nonces not needed for Noise => handshake object
These commented out things need to be cleaned up.

How much work would it be to make the new protocol optional (either by compile time flag or a Tox_Options field)?

2021-12-02 21:25 UTC, iphydf commented on toxcore/net_crypto.c
> +            noise_perror("write handshake", err);
This probably needs to become a LOGGER statement so we don't write to stderr from a library.

2021-12-02 21:25 UTC, iphydf commented on toxcore/net_crypto.c
> +    if (role == NOISE_ROLE_RESPONDER) {
This whole nested if/else statement can be a single if.

2021-12-02 21:25 UTC, iphydf commented on toxcore/net_crypto.c
> +        if (peer_public_key) {
Invert check to return early and reduce nesting.

2021-12-02 21:25 UTC, iphydf commented on toxcore/net_crypto.c
> +    if (role == NOISE_ROLE_RESPONDER) {
Invert condition/return early.

2024-03-22 13:34 UTC, goldroom commented
Closing in favor of https://github.com/TokTok/c-toxcore/pull/2450.

2024-03-22 13:34 UTC, closed without merging