cleanup: refactor toxav_call_control
TokTok/c-toxcore pull request #1841
Opened 2022-01-02 21:33 UTC by JFreegman

Control logic is now placed in control-specific helper functions instead of having one giant confusing function that does everything.

2022-01-03 12:41 UTC, iphydf requested changes

2022-01-03 12:41 UTC, iphydf commented on toxav/toxav.c
> +    if (call->msi_call->self_capabilities == 0 && call->previous_self_capabilities) {
```c
{
    if (call->msi_call->self_capabilities != 0 || call->previous_self_capabilities == 0) {
        *rc = TOXAV_ERR_CALL_CONTROL_INVALID_TRANSITION;
        return;
    }

    if (msi_change_capabilities(call->msi_call, call->previous_self_capabilities) == -1) {
        *rc = TOXAV_ERR_CALL_CONTROL_SYNC;
        return;
    }

    rtp_allow_receiving(call->audio_rtp);
    rtp_allow_receiving(call->video_rtp);
}
```

The same for all the others below. Reduce nesting by using early returns.

2022-01-03 12:41 UTC, iphydf commented on toxav/toxav.c
> +            call_control_handle_resume(call, &rc);
If all these handle functions return their error code, OK on success, we don't need to use out-parameters here. That seems a bit cleaner to me.

2022-01-09 09:39 UTC, sudden6 approved these changes
<img class="emoji" title=":lgtm_strong:" alt=":lgtm_strong:" align="absmiddle" src="https://reviewable.io/lgtm_strong.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/toktok/c-toxcore/1841#-:-MsyCCQNEcwo0Q98A2kp:b-jbsf8z)* status: :shipit: complete! 1 change requests, 1 of 1 approvals obtained (waiting on @JFreegman)



<!-- Sent from Reviewable.io -->

2022-01-13 23:11 UTC, merged