feat: add DHT queries to private API
TokTok/c-toxcore pull request #1935
Opened 2022-01-28 15:46 UTC by JFreegman

This PR adds functionality for clients to send DHT getnodes requests to their DHT peers. It also allows clients to make queries on DHT nodes that they receive in a getnodes response, including port, private key, and IP address (as a null terminated string). 

A typical use case would be for a DHT network crawler, but it could also be used for understanding and diagnosing DHT network behaviour.

2022-01-29 16:52 UTC, iphydf requested changes
> Reviewed 2 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/toktok/c-toxcore/1935)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @JFreegman)

___
*[toxcore/DHT.c, line 1779 at r1](https://reviewable.io/reviews/toktok/c-toxcore/1935#-Muaj8Jh4qrU5DXB62AS:-Muaj8Jh4qrU5DXB62AT:b-gkkgke) ([raw file](https://github.com/toktok/c-toxcore/blob/b63ea209814b3e47ebefe0c062bdb6cce637fcf4/toxcore/DHT.c#L1779)):*
> ```C
> {
>     const int ret = getnodes(dht, *from_ipp, from_id, which_id);
>     return ret < 0 ? -1 : 0;
> ```

This is a binary result (-1 or 0). Should we return bool?
___
*[toxcore/tox.c, line 19 at r1](https://reviewable.io/reviews/toktok/c-toxcore/1935#-MuajJgyEv2yuOC6T1BM:-MuajJgyEv2yuOC6T1BN:bjxc96z) ([raw file](https://github.com/toktok/c-toxcore/blob/b63ea209814b3e47ebefe0c062bdb6cce637fcf4/toxcore/tox.c#L19)):*
> ```C
> #include <winsock2.h>
> #else
> #include <arpa/inet.h>
> ```

Is there a way we could use the "network.h" abstraction instead of introducing system specifics at the highest layer?
___
*[toxcore/tox.c, line 311 at r1](https://reviewable.io/reviews/toktok/c-toxcore/1935#-MuajWtK5lrXdHCP9Ak-:-MuajWtK5lrXdHCP9Ak0:bvhhhy9) ([raw file](https://github.com/toktok/c-toxcore/blob/b63ea209814b3e47ebefe0c062bdb6cce637fcf4/toxcore/tox.c#L311)):*
> ```C
>     struct Tox_Userdata *tox_data = (struct Tox_Userdata *)user_data;
> 
>     if (tox_data->tox->dht_get_nodes_response_callback != nullptr) {
> ```

If it is nullptr, return. We don't do that in the others because the "then" case is very short. Here, we can benefit from early return and less nesting.
___
*[toxcore/tox_private.h, line 127 at r1](https://reviewable.io/reviews/toktok/c-toxcore/1935#-Muak2QP9LmJ0ZVutUKo:-Muak2QP9LmJ0ZVutUKp:b-33qlk0) ([raw file](https://github.com/toktok/c-toxcore/blob/b63ea209814b3e47ebefe0c062bdb6cce637fcf4/toxcore/tox_private.h#L127)):*
> ```objc
>  *   function returns 0.
>  */
> uint16_t tox_dht_node_get_port(const Tox_Dht_Node *dht_node);
> ```

Instead of all these, can we just pass the exploded struct as arguments to the callback? Pass port, pkey, ip, etc. all in the same callback invocation.


<!-- Sent from Reviewable.io -->

2022-01-29 18:58 UTC, JFreegman reviewed
> *[Reviewable](https://reviewable.io/reviews/toktok/c-toxcore/1935)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @iphydf)

___
*[toxcore/DHT.c, line 1779 at r1](https://reviewable.io/reviews/toktok/c-toxcore/1935#-Muaj8Jh4qrU5DXB62AS:-MubBmgA76v_PaVmxUeB:b-896fix) ([raw file](https://github.com/toktok/c-toxcore/blob/b63ea209814b3e47ebefe0c062bdb6cce637fcf4/toxcore/DHT.c#L1779)):*
<details><summary><i>Previously, iphydf wrote…</i></summary><blockquote>

This is a binary result (-1 or 0). Should we return bool?
</blockquote></details>

Done.
___
*[toxcore/tox.c, line 19 at r1](https://reviewable.io/reviews/toktok/c-toxcore/1935#-MuajJgyEv2yuOC6T1BM:-MubBqj83opqOasQ5mzX:b-896fix) ([raw file](https://github.com/toktok/c-toxcore/blob/b63ea209814b3e47ebefe0c062bdb6cce637fcf4/toxcore/tox.c#L19)):*
<details><summary><i>Previously, iphydf wrote…</i></summary><blockquote>

Is there a way we could use the "network.h" abstraction instead of introducing system specifics at the highest layer?
</blockquote></details>

Done.
___
*[toxcore/tox.c, line 311 at r1](https://reviewable.io/reviews/toktok/c-toxcore/1935#-MuajWtK5lrXdHCP9Ak-:-MubBrt-0oo_O-uydEOp:b-896fix) ([raw file](https://github.com/toktok/c-toxcore/blob/b63ea209814b3e47ebefe0c062bdb6cce637fcf4/toxcore/tox.c#L311)):*
<details><summary><i>Previously, iphydf wrote…</i></summary><blockquote>

If it is nullptr, return. We don't do that in the others because the "then" case is very short. Here, we can benefit from early return and less nesting.
</blockquote></details>

Done.
___
*[toxcore/tox_private.h, line 127 at r1](https://reviewable.io/reviews/toktok/c-toxcore/1935#-Muak2QP9LmJ0ZVutUKo:-MubBp2V3kAbLD3bNlOK:b-896fix) ([raw file](https://github.com/toktok/c-toxcore/blob/b63ea209814b3e47ebefe0c062bdb6cce637fcf4/toxcore/tox_private.h#L127)):*
<details><summary><i>Previously, iphydf wrote…</i></summary><blockquote>

Instead of all these, can we just pass the exploded struct as arguments to the callback? Pass port, pkey, ip, etc. all in the same callback invocation.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-01-30 00:07 UTC, robinlinden approved these changes

2022-01-30 00:13 UTC, JFreegman commented on toxcore/tox_private.h
> +uint32_t tox_dht_node_ip_string_size(void);
It doesn't like the lack of respective function definitions in tox.c. I don't know why it doesn't complain about the ones in tox.h.

2022-01-31 22:59 UTC, sudden6 reviewed
testcase and API change <img class="emoji" title=":lgtm_strong:" alt=":lgtm_strong:" align="absmiddle" src="https://reviewable.io/lgtm_strong.png" height="20" width="61"/> 

> Reviewed 1 of 6 files at r1, 2 of 4 files at r3, 3 of 3 files at r5, 4 of 4 files at r6.
> *[Reviewable](https://reviewable.io/reviews/toktok/c-toxcore/1935#-:-MumMJNi4Hz9TbhEFBs_:bsxs9na)* status: :shipit: complete! 1 change requests, 1 of 1 approvals obtained (waiting on @iphydf and @robinlinden)



<!-- Sent from Reviewable.io -->

2022-02-09 12:09 UTC, iphydf approved these changes

2022-02-10 15:43 UTC, merged