cleanup: Remove *all* boolean-int conversions.
TokTok/c-toxcore pull request #2120
Opened 2022-02-26 23:51 UTC by iphydf

These were found by the new cimple type check which is completely
unforgiving to implicit boolean conversions. After this PR, there should
be no more implicit int-to-bool or bool-to-int conversions.

2022-02-27 03:04 UTC, JFreegman approved these changes
> Reviewed 17 of 17 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/toktok/c-toxcore/2120)* status: :shipit: complete! 1 of 1 approvals obtained



<!-- Sent from Reviewable.io -->

2022-02-27 13:21 UTC, sudden6 requested changes
> *[Reviewable](https://reviewable.io/reviews/toktok/c-toxcore/2120)* status: :shipit: complete! 1 change requests, 1 of 1 approvals obtained (waiting on @iphydf)

___
*[toxcore/DHT.c, line 1418 at r1](https://reviewable.io/reviews/toktok/c-toxcore/2120#-MwvKf5Z1VnrPkPeYBJt:-MwvKf5Z1VnrPkPeYBJu:bo18qmb) ([raw file](https://github.com/toktok/c-toxcore/blob/3ef96f70965f9958922e81213bcb2cb8bf3c2ea7/toxcore/DHT.c#L1418)):*
> ```C
> 
> non_null()
> static int handle_getnodes(void *object, const IP_Port *source, const uint8_t *packet, uint16_t length, void *userdata)
> ```

why `int` here but you changed the return type of a function below?


<!-- Sent from Reviewable.io -->

2022-02-28 10:08 UTC, iphydf reviewed
> *[Reviewable](https://reviewable.io/reviews/toktok/c-toxcore/2120)* status: :shipit: complete! 1 change requests, 1 of 1 approvals obtained (waiting on @sudden6)

___
*[toxcore/DHT.c, line 1418 at r1](https://reviewable.io/reviews/toktok/c-toxcore/2120#-MwvKf5Z1VnrPkPeYBJt:-MwznHZj9D9BGE-tEJxn:b-upvjrm) ([raw file](https://github.com/toktok/c-toxcore/blob/3ef96f70965f9958922e81213bcb2cb8bf3c2ea7/toxcore/DHT.c#L1418)):*
<details><summary><i>Previously, sudden6 wrote…</i></summary><blockquote>

why `int` here but you changed the return type of a function below?
</blockquote></details>

This is a callback handler. The one below isn't.


<!-- Sent from Reviewable.io -->

2022-02-28 12:47 UTC, sudden6 approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/toktok/c-toxcore/2120)* status: :shipit: complete! 1 of 1 approvals obtained



<!-- Sent from Reviewable.io -->

2022-02-28 14:00 UTC, merged