feat: Merge the remainder of the new groupchats implementation
TokTok/c-toxcore pull request #2269
Opened 2022-04-08 14:58 UTC by JFreegman

Commit history: https://github.com/jfreegman/toxcore/tree/ngc_jf
Spec: https://toktok.ltd/spec.html#dht-group-chats

2022-04-08 18:21 UTC, iphydf requested changes

2022-04-08 18:21 UTC, iphydf commented on other/analysis/run-cppcheck
> +# TODO(iphydf): False positives
No TODO for me please :).

2022-04-08 18:21 UTC, iphydf commented on toxcore/LAN_discovery.c
> +                        uint16_t port)
Maybe you can make a PR with all the formatting changes (run astyle; make PR) first?

2022-04-11 15:13 UTC, JFreegman reviewed
> *[Reviewable](https://reviewable.io/reviews/toktok/c-toxcore/2269)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @iphydf)

___
*[other/analysis/run-cppcheck, line 24 at r1](https://reviewable.io/reviews/toktok/c-toxcore/2269#-N-8ftbu5YEBl1-OH0DL-r1-24:-N-OAoN6EHBblcagCa0q:b-896fix) ([raw file](https://github.com/toktok/c-toxcore/blob/77f6b54a3fb96ceec261ac8da90d51e8c71bfe35/other/analysis/run-cppcheck#L24)):*
<details><summary><i>Previously, iphydf wrote…</i></summary><blockquote>

No TODO for me please :).
</blockquote></details>

Done.
___
*[toxcore/LAN_discovery.c, line 343 at r1](https://reviewable.io/reviews/toktok/c-toxcore/2269#-N-8ftbu5YEBl1-OH0DS-r1-343:-N-OApnZCHcuhfTxMyca:b1ciuhp) ([raw file](https://github.com/toktok/c-toxcore/blob/77f6b54a3fb96ceec261ac8da90d51e8c71bfe35/toxcore/LAN_discovery.c#L343)):*
<details><summary><i>Previously, iphydf wrote…</i></summary><blockquote>

Maybe you can make a PR with all the formatting changes (run astyle; make PR) first?
</blockquote></details>

Probably a bad idea since my astyle formats differently from whatever the latest version is


<!-- Sent from Reviewable.io -->

2022-04-19 19:39 UTC, sudden6 requested changes
AFAICT at least the new auto_tests are missing a license and copyright info.

> Reviewed 19 of 60 files at r1, 6 of 14 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/toktok/c-toxcore/2269#-:-N02KQZf5702ImHOz1zW:bngig1t)* status: 2 change requests, 0 of 1 approvals obtained (waiting on @iphydf and @JFreegman)

___
*[auto_tests/group_invite_test.c, line 50 at r2](https://reviewable.io/reviews/toktok/c-toxcore/2269#-N02HsMMByEzz6pzY6Nx:-N02HsMMByEzz6pzY6Ny:b-bbif0l) ([raw file](https://github.com/toktok/c-toxcore/blob/7b52d02d41bfe786cd9969a7bdee8f85872ce93b/auto_tests/group_invite_test.c#L50)):*
> ```C
>         return false;
>     }
> ```

whitespace issue
___
*[toxcore/Messenger.c, line 368 at r2](https://reviewable.io/reviews/toktok/c-toxcore/2269#-N02Ir-j8rMng5dW0YJb:-N02Ir-j8rMng5dW0YJc:bba4vk4) ([raw file](https://github.com/toktok/c-toxcore/blob/7b52d02d41bfe786cd9969a7bdee8f85872ce93b/toxcore/Messenger.c#L368)):*
> ```C
> /** @brief the friend connection and onion connection for a groupchat.
>  *
>  * @retval 0 if success.
> ```

Documentation doesn't match implementation type


<!-- Sent from Reviewable.io -->

2022-04-19 23:51 UTC, iphydf requested changes

2022-04-19 23:51 UTC, iphydf commented on toxcore/Messenger.h
> +// TODO(Jfreegman, Iphy): Remove this before merge
What needs to be done to remove this?

2022-04-19 23:51 UTC, iphydf commented on toxcore/Messenger.h
> +/* Initializes the friend connection and onion connection for a groupchat.
Change to `/**` style comment. Same below.

2022-04-19 23:51 UTC, iphydf commented on toxcore/Messenger.c
> +/*
`/**`

2022-04-21 19:49 UTC, sudden6 requested changes
> Reviewed 15 of 60 files at r1, 4 of 14 files at r2, 2 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/toktok/c-toxcore/2269)* status: 2 change requests, 0 of 1 approvals obtained (waiting on @iphydf, @JFreegman, and @sudden6)

___
*[auto_tests/group_moderation_test.c, line 50 at r4](https://reviewable.io/reviews/toktok/c-toxcore/2269#-N0CTs9A4XsVieaFav--:-N0CTs9A4XsVieaFav-0:b-wiuyma) ([raw file](https://github.com/toktok/c-toxcore/blob/2904fbdd42c216322c844568aadb319675a8c6af/auto_tests/group_moderation_test.c#L50)):*
> ```C
>     size_t user_event_count;
> 
>     bool kick_check;  // moderater gets kicked
> ```

typo, `moderator`
___
*[auto_tests/group_moderation_test.c, line 493 at r4](https://reviewable.io/reviews/toktok/c-toxcore/2269#-N0CUt6z7_gy5mPxzSt2:-N0CUt6z7_gy5mPxzSt3:b-cg36bx) ([raw file](https://github.com/toktok/c-toxcore/blob/2904fbdd42c216322c844568aadb319675a8c6af/auto_tests/group_moderation_test.c#L493)):*
> ```C
>     do {
>         iterate_all_wait(autotoxes, NUM_GROUP_TOXES, ITERATION_INTERVAL);
>     } while (!all_peers_connected(autotoxes));
> ```

should this loop have a timeout?
___
*[auto_tests/group_topic_test.c, line 98 at r4](https://reviewable.io/reviews/toktok/c-toxcore/2269#-N0CW2pE9u0jHdekuCo5:-N0CW2pE9u0jHdekuCo6:b-r198xs) ([raw file](https://github.com/toktok/c-toxcore/blob/2904fbdd42c216322c844568aadb319675a8c6af/auto_tests/group_topic_test.c#L98)):*
> ```C
>  * Return -1 on failure.
>  */
> static int set_topic(Tox *tox, uint32_t groupnumber, const char *topic, size_t length)
> ```

probably better to use bool here
___
*[other/analysis/variants.sh, line 4 at r4](https://reviewable.io/reviews/toktok/c-toxcore/2269#-N0CWiHQ1kWgNBTmvBB7:-N0CWiHQ1kWgNBTmvBB8:bv2pw9m) ([raw file](https://github.com/toktok/c-toxcore/blob/50094b73851b96081f370318cdbc1b5656722433/other/analysis/variants.sh#L4)):*
> ```Shell
> 
> run "$@"
> run -DVANILLA_NACL -I/usr/include/sodium "$@"
> ```

why is that removed, is Vanilla NaCl not supported anymore?
___
*[toxcore/group_chats.h, line 62 at r4](https://reviewable.io/reviews/toktok/c-toxcore/2269#-N0CXB_UDp7MnG0F_fj_:-N0CXB_UDp7MnG0F_fja:b6hcoe0) ([raw file](https://github.com/toktok/c-toxcore/blob/2904fbdd42c216322c844568aadb319675a8c6af/toxcore/group_chats.h#L62)):*
> ```objc
> /** Group broadcast packet types */
> typedef enum Group_Broadcast_Type {
>     GM_STATUS          = 0x00,  // Peer changed their status
> ```

nit: why the `GM_` prefix, doesn't fit `Group_Broadcats_Type` IMHO
___
*[toxcore/group_chats.h, line 150 at r4](https://reviewable.io/reviews/toktok/c-toxcore/2269#-N0CXcA61aFruJ9ex8xT:-N0CXcA61aFruJ9ex8xU:bdhgvcp) ([raw file](https://github.com/toktok/c-toxcore/blob/2904fbdd42c216322c844568aadb319675a8c6af/toxcore/group_chats.h#L150)):*
> ```objc
>  * `pakcket_type` must be either NET_PACKET_GC_LOSSY or NET_PACKET_GC_LOSSLESS.
>  */
> uint16_t gc_get_wrapped_packet_size(uint16_t length, uint8_t packet_type);
> ```

can `packet_type` be turned into an enum if it has only two named values that work? Is there a possible error condition and how is it signaled? I suspect at least `length` has an upper bound.
___
*[toxcore/group_chats.h, line 201 at r4](https://reviewable.io/reviews/toktok/c-toxcore/2269#-N0CY6OY35dDqQJMg9S1:-N0CY6OY35dDqQJMg9S2:b-jwvi6q) ([raw file](https://github.com/toktok/c-toxcore/blob/2904fbdd42c216322c844568aadb319675a8c6af/toxcore/group_chats.h#L201)):*
> ```objc
>  */
> non_null()
> int gc_toggle_ignore(const GC_Chat *chat, uint32_t peer_id, bool ignore);
> ```

nit: IMHO it's less of a `toggle` but more a setter function, because of the `ignore` parameter
___
*[toxcore/group_chats.h, line 407 at r4](https://reviewable.io/reviews/toktok/c-toxcore/2269#-N0CZ9hM9DPkU1DRprSJ:-N0CZ9hM9DPkU1DRprSK:b7pnxfo) ([raw file](https://github.com/toktok/c-toxcore/blob/2904fbdd42c216322c844568aadb319675a8c6af/toxcore/group_chats.h#L407)):*
> ```objc
> 
> /** @brief Returns the group role of peer designated by `peer_id`.
>  * Returns (uint8_t)-1 on failure.
> ```

How about `UINT8_MAX` here?
___
*[toxcore/group_chats.h, line 710 at r4](https://reviewable.io/reviews/toktok/c-toxcore/2269#-N0CZmYMBanfGPr4_6MQ:-N0CZmYMBanfGPr4_6MR:b-jdgsqt) ([raw file](https://github.com/toktok/c-toxcore/blob/2904fbdd42c216322c844568aadb319675a8c6af/toxcore/group_chats.h#L710)):*
> ```objc
>  * Note: This function may modify the peer list and change peer numbers.
>  *
>  * Return 0 if packet is successfully handled.
> ```

how about returning `bool` here?
___
*[toxcore/group_chats.h, line 719 at r4](https://reviewable.io/reviews/toktok/c-toxcore/2269#-N0CZqCj-2S-puoKyoCH:-N0CZqCj-2S-puoKyoCI:bb7od0r) ([raw file](https://github.com/toktok/c-toxcore/blob/2904fbdd42c216322c844568aadb319675a8c6af/toxcore/group_chats.h#L719)):*
> ```objc
> /** @brief Handles an invite accept packet.
>  *
>  * Return 0 on success.
> ```

same
___
*[toxcore/group_chats.c, line 71 at r4](https://reviewable.io/reviews/toktok/c-toxcore/2269#-N0C_8rY8_yPGy3IdAt6:-N0C_8rY8_yPGy3IdAt7:b1tr1o7) ([raw file](https://github.com/toktok/c-toxcore/blob/2904fbdd42c216322c844568aadb319675a8c6af/toxcore/group_chats.c#L71)):*
> ```C
> 
> /* Maximum number of bytes to pad packets with */
> #define GC_MAX_PACKET_PADDING 8
> ```

Why is this padded? and why 8 bytes?
___
*[toxcore/group_chats.c, line 82 at r4](https://reviewable.io/reviews/toktok/c-toxcore/2269#-N0C_Ocv27zaQc7OCJSt:-N0C_Ocv27zaQc7OCJSu:b-qkhc2v) ([raw file](https://github.com/toktok/c-toxcore/blob/2904fbdd42c216322c844568aadb319675a8c6af/toxcore/group_chats.c#L82)):*
> ```C
> 
> /* How often we try to handshake with an unconfirmed peer */
> #define GC_SEND_HANDSHAKE_INTERVAL 3
> ```

please include the unit of time in the comment or define name (for subsecond units).
___
*[toxcore/group_chats.c, line 85 at r4](https://reviewable.io/reviews/toktok/c-toxcore/2269#-N0C_clfAvdwu-wJRYwa:-N0C_I6jBInZxheBDtiZ:bb7od0r) ([raw file](https://github.com/toktok/c-toxcore/blob/2904fbdd42c216322c844568aadb319675a8c6af/toxcore/group_chats.c#L85)):*
> ```C
> 
> /* How often we rotate session encryption keys with a peer */
> #define GC_KEY_ROTATION_TIMEOUT (5 * 60)
> ```

same
___
*[toxcore/group_chats.c, line 88 at r4](https://reviewable.io/reviews/toktok/c-toxcore/2269#-N0C_fPQB5gsYa3JQ1ht:-N0C_fPQB5gsYa3JQ1hu:bb7od0r) ([raw file](https://github.com/toktok/c-toxcore/blob/2904fbdd42c216322c844568aadb319675a8c6af/toxcore/group_chats.c#L88)):*
> ```C
> 
> /* How often we try to reconnect to peers that recently timed out */
> #define GC_TIMED_OUT_RECONN_TIMEOUT (GC_UNCONFIRMED_PEER_TIMEOUT * 3)
> ```

same
___
*[toxcore/group_chats.c, line 90 at r4](https://reviewable.io/reviews/toktok/c-toxcore/2269#-N0C_heADhqJRbJQeogE:-N0C_heADhqJRbJQeogF:bb7od0r) ([raw file](https://github.com/toktok/c-toxcore/blob/2904fbdd42c216322c844568aadb319675a8c6af/toxcore/group_chats.c#L90)):*
> ```C
> #define GC_TIMED_OUT_RECONN_TIMEOUT (GC_UNCONFIRMED_PEER_TIMEOUT * 3)
> 
> /* How long before we stop trying to reconnect with a timed out peer */
> ```

same
___
*[toxcore/group_chats.c, line 353 at r4](https://reviewable.io/reviews/toktok/c-toxcore/2269#-N0CaRNnDlsgQ7cJIRN1:-N0CaRNnDlsgQ7cJIRN2:b-srsc67) ([raw file](https://github.com/toktok/c-toxcore/blob/2904fbdd42c216322c844568aadb319675a8c6af/toxcore/group_chats.c#L353)):*
> ```C
> 
> non_null()
> static bool saved_peer_is_valid(const GC_SavedPeerInfo *saved_peer);
> ```

maybe move that one to the others on top?
___
*[toxcore/group_chats.c, line 624 at r4](https://reviewable.io/reviews/toktok/c-toxcore/2269#-N0Cb9gr72nA4_eQBHpZ:-N0Cb9gr72nA4_eQBHp_:bihyvym) ([raw file](https://github.com/toktok/c-toxcore/blob/2904fbdd42c216322c844568aadb319675a8c6af/toxcore/group_chats.c#L624)):*
> ```C
>     }
> 
>     uint32_t index = random_u32(chat->rng) % chat->numpeers;
> ```

`crypto_core.h` has `random_range_u32(...)` which does exactly what's done here, add an offset of `1` and you even save some lines.
___
*[toxcore/g [...]

2022-04-22 15:59 UTC, JFreegman reviewed
None of the auto tests have license/copyright info 

> *[Reviewable](https://reviewable.io/reviews/toktok/c-toxcore/2269#-:-N0GjKnJ8S--f4wr6D9m:bbvaxny)* status: 2 change requests, 0 of 1 approvals obtained (waiting on @iphydf and @sudden6)

___
*[auto_tests/group_moderation_test.c, line 493 at r4](https://reviewable.io/reviews/toktok/c-toxcore/2269#-N0CUt6z7_gy5mPxzSt2:-N0GjUeV4NVJpm5cwpe2:b-hzsbjz) ([raw file](https://github.com/toktok/c-toxcore/blob/2904fbdd42c216322c844568aadb319675a8c6af/auto_tests/group_moderation_test.c#L493)):*
<details><summary><i>Previously, sudden6 wrote…</i></summary><blockquote>

should this loop have a timeout?
</blockquote></details>

Nope, see Iphy's answer in IRC
___
*[auto_tests/group_topic_test.c, line 98 at r4](https://reviewable.io/reviews/toktok/c-toxcore/2269#-N0CW2pE9u0jHdekuCo5:-N0Gk2HKERmaeTm9IGn0:b-896fix) ([raw file](https://github.com/toktok/c-toxcore/blob/2904fbdd42c216322c844568aadb319675a8c6af/auto_tests/group_topic_test.c#L98)):*
<details><summary><i>Previously, sudden6 wrote…</i></summary><blockquote>

probably better to use bool here
</blockquote></details>

Done.
___
*[other/analysis/variants.sh, line 4 at r4](https://reviewable.io/reviews/toktok/c-toxcore/2269#-N0CWiHQ1kWgNBTmvBB7:-N0Gk4iA2d668L1otBIE:b-7o2bxu) ([raw file](https://github.com/toktok/c-toxcore/blob/50094b73851b96081f370318cdbc1b5656722433/other/analysis/variants.sh#L4)):*
<details><summary><i>Previously, sudden6 wrote…</i></summary><blockquote>

why is that removed, is Vanilla NaCl not supported anymore?
</blockquote></details>

NaCl was building with a ton of unused function warnings which was blocking development. 
___
*[toxcore/group_chats.h, line 62 at r4](https://reviewable.io/reviews/toktok/c-toxcore/2269#-N0CXB_UDp7MnG0F_fj_:-N0Gkz3y3Zx522Fpbu_8:brui6fe) ([raw file](https://github.com/toktok/c-toxcore/blob/2904fbdd42c216322c844568aadb319675a8c6af/toxcore/group_chats.h#L62)):*
<details><summary><i>Previously, sudden6 wrote…</i></summary><blockquote>

nit: why the `GM_` prefix, doesn't fit `Group_Broadcats_Type` IMHO
</blockquote></details>

I'm reluctant to change any of the enum prefixes because we will probably end up changing them all again in the future to satisfy cimple
___
*[toxcore/group_chats.h, line 150 at r4](https://reviewable.io/reviews/toktok/c-toxcore/2269#-N0CXcA61aFruJ9ex8xT:-N0GlIn28W7KzrAtRbG7:b-9bop6o) ([raw file](https://github.com/toktok/c-toxcore/blob/2904fbdd42c216322c844568aadb319675a8c6af/toxcore/group_chats.h#L150)):*
<details><summary><i>Previously, sudden6 wrote…</i></summary><blockquote>

can `packet_type` be turned into an enum if it has only two named values that work? Is there a possible error condition and how is it signaled? I suspect at least `length` has an upper bound.
</blockquote></details>

Done. Changed it to the Net_Packet_Type enum. Asserts are used to check length bounds.
___
*[toxcore/group_chats.h, line 201 at r4](https://reviewable.io/reviews/toktok/c-toxcore/2269#-N0CY6OY35dDqQJMg9S1:-N0GqnMI29geSn51GjNY:b-896fix) ([raw file](https://github.com/toktok/c-toxcore/blob/2904fbdd42c216322c844568aadb319675a8c6af/toxcore/group_chats.h#L201)):*
<details><summary><i>Previously, sudden6 wrote…</i></summary><blockquote>

nit: IMHO it's less of a `toggle` but more a setter function, because of the `ignore` parameter
</blockquote></details>

Done.
___
*[toxcore/group_chats.h, line 407 at r4](https://reviewable.io/reviews/toktok/c-toxcore/2269#-N0CZ9hM9DPkU1DRprSJ:-N0GrhBW4eZJtaCsNjU6:b-896fix) ([raw file](https://github.com/toktok/c-toxcore/blob/2904fbdd42c216322c844568aadb319675a8c6af/toxcore/group_chats.h#L407)):*
<details><summary><i>Previously, sudden6 wrote…</i></summary><blockquote>

How about `UINT8_MAX` here?
</blockquote></details>

Done.
___
*[toxcore/group_chats.h, line 710 at r4](https://reviewable.io/reviews/toktok/c-toxcore/2269#-N0CZmYMBanfGPr4_6MQ:-N0GsJtw5bLx62VUl17P:b-896fix) ([raw file](https://github.com/toktok/c-toxcore/blob/2904fbdd42c216322c844568aadb319675a8c6af/toxcore/group_chats.h#L710)):*
<details><summary><i>Previously, sudden6 wrote…</i></summary><blockquote>

how about returning `bool` here?
</blockquote></details>

Done.
___
*[toxcore/group_chats.h, line 719 at r4](https://reviewable.io/reviews/toktok/c-toxcore/2269#-N0CZqCj-2S-puoKyoCH:-N0Gt5F72_WC0fDbhhaV:b-896fix) ([raw file](https://github.com/toktok/c-toxcore/blob/2904fbdd42c216322c844568aadb319675a8c6af/toxcore/group_chats.h#L719)):*
<details><summary><i>Previously, sudden6 wrote…</i></summary><blockquote>

same
</blockquote></details>

Done.
___
*[toxcore/group_chats.c, line 71 at r4](https://reviewable.io/reviews/toktok/c-toxcore/2269#-N0C_8rY8_yPGy3IdAt6:-N0Gt6_fCG0nYgtFsuBd:b4h17mv) ([raw file](https://github.com/toktok/c-toxcore/blob/2904fbdd42c216322c844568aadb319675a8c6af/toxcore/group_chats.c#L71)):*
<details><summary><i>Previously, sudden6 wrote…</i></summary><blockquote>

Why is this padded? and why 8 bytes?
</blockquote></details>

Done. Added a comment.
___
*[toxcore/group_chats.c, line 82 at r4](https://reviewable.io/reviews/toktok/c-toxcore/2269#-N0C_Ocv27zaQc7OCJSt:-N0Gu9ir3InXfgCCxBf9:b-896fix) ([raw file](https://github.com/toktok/c-toxcore/blob/2904fbdd42c216322c844568aadb319675a8c6af/toxcore/group_chats.c#L82)):*
<details><summary><i>Previously, sudden6 wrote…</i></summary><blockquote>

please include the unit of time in the comment or define name (for subsecond units).
</blockquote></details>

Done.
___
*[toxcore/group_chats.c, line 85 at r4](https://reviewable.io/reviews/toktok/c-toxcore/2269#-N0C_clfAvdwu-wJRYwa:-N0GuABsDiz2sEo2EXx2:b-896fix) ([raw file](https://github.com/toktok/c-toxcore/blob/2904fbdd42c216322c844568aadb319675a8c6af/toxcore/group_chats.c#L85)):*
<details><summary><i>Previously, sudden6 wrote…</i></summary><blockquote>

same
</blockquote></details>

Done.
___
*[toxcore/group_chats.c, line 88 at r4](https://reviewable.io/reviews/toktok/c-toxcore/2269#-N0C_fPQB5gsYa3JQ1ht:-N0GuAbj2-x8VqvCwtmB:b-896fix) ([raw file](https://github.com/toktok/c-toxcore/blob/2904fbdd42c216322c844568aadb319675a8c6af/toxcore/group_chats.c#L88)):*
<details><summary><i>Previously, sudden6 wrote…</i></summary><blockquote>

same
</blockquote></details>

Done.
___
*[toxcore/group_chats.c, line 90 at r4](https://reviewable.io/reviews/toktok/c-toxcore/2269#-N0C_heADhqJRbJQeogE:-N0GuAzU68gMa0nwXB88:b-896fix) ([raw file](https://github.com/toktok/c-toxcore/blob/2904fbdd42c216322c844568aadb319675a8c6af/toxcore/group_chats.c#L90)):*
<details><summary><i>Previously, sudden6 wrote…</i></summary><blockquote>

same
</blockquote></details>

Done.
___
*[toxcore/group_chats.c, line 353 at r4](https://reviewable.io/reviews/toktok/c-toxcore/2269#-N0CaRNnDlsgQ7cJIRN1:-N0GuUNC7KSAAhDFyGZu:b-896fix) ([raw file](https://github.com/toktok/c-toxcore/blob/2904fbdd42c216322c844568aadb319675a8c6af/toxcore/group_chats.c#L353)):*
<details><summary><i>Previously, sudden6 wrote…</i></summary><blockquote>

maybe move that one to the others on top?
</blockquote></details>

Done.
___
*[toxcore/group_chats.c, line 624 at r4](https://reviewable.io/reviews/toktok/c-toxcore/2269#-N0Cb9gr72nA4_eQBHpZ:-N0Guo582fA-SY7roa71:bs7wumx) ([raw file](https://github.com/toktok/c-toxcore/blob/2904fbdd42c216322c844568aadb319675a8c6af/toxcore/group_chats.c#L624)):*
<details><summary><i>Previously, sudden6 wrote…</i></summary><blockquote>

`crypto_core.h` has `random_range_u32(...)` which does exactly what's done here, add an offset of `1` and you even save some lines.
</blockquote></details>

Done. 
___
*[toxcore/group_chats.c, line 1854 at r4](https://reviewable.io/reviews/toktok/c-toxcore/2269#-N0CcpeA2LkXG3ppicTx:-N0GxVPsBbdB0VxX4e3K:b-8a5cm2) ([raw file](https://github.com/toktok/c-toxcore/blob/2904fbdd42c216322c844568aadb319675a8c6af/toxcore/group_chats.c#L1854)):*
<details><summary><i>Previously, sudden6 wrote…</i></summary><blockquote>

else what? Is this part of the protocol definition?
</blockquote></details>

Validation won't work  [...]

2022-04-22 20:01 UTC, sudden6 requested changes
Ok, probably should discuss this outside this PR

> Reviewed 9 of 60 files at r1, 1 of 14 files at r2, 1 of 4 files at r3, 1 of 1 files at r4, 5 of 12 files at r5.
> *[Reviewable](https://reviewable.io/reviews/toktok/c-toxcore/2269#-:-N0HW_lx4zrVlcuktl1A:b-il15ec)* status: 2 change requests, 0 of 1 approvals obtained (waiting on @iphydf and @JFreegman)

___
*[auto_tests/group_moderation_test.c, line 493 at r4](https://reviewable.io/reviews/toktok/c-toxcore/2269#-N0CUt6z7_gy5mPxzSt2:-N0HYXNx2ZNmZgt-8bJH:b-lxf4qv) ([raw file](https://github.com/toktok/c-toxcore/blob/2904fbdd42c216322c844568aadb319675a8c6af/auto_tests/group_moderation_test.c#L493)):*
<details><summary><i>Previously, JFreegman wrote…</i></summary><blockquote>

Nope, see Iphy's answer in IRC
</blockquote></details>

yeah, was being stupid here.
___
*[auto_tests/group_topic_test.c, line 106 at r5](https://reviewable.io/reviews/toktok/c-toxcore/2269#-N0HWogd7Qrey7EWzPaq:-N0HWogd7Qrey7EWzPar:bl6an1u) ([raw file](https://github.com/toktok/c-toxcore/blob/4ba058d2f700d2257597eda0fa70bff2e98c0bdc/auto_tests/group_topic_test.c#L106)):*
> ```C
>     }
> 
>     return true;
> ```

can be simplified to a oneliner now
___
*[other/analysis/variants.sh, line 4 at r4](https://reviewable.io/reviews/toktok/c-toxcore/2269#-N0CWiHQ1kWgNBTmvBB7:-N0HWwYl9QQEhi8JB9PA:bpdu3jv) ([raw file](https://github.com/toktok/c-toxcore/blob/50094b73851b96081f370318cdbc1b5656722433/other/analysis/variants.sh#L4)):*
<details><summary><i>Previously, JFreegman wrote…</i></summary><blockquote>

NaCl was building with a ton of unused function warnings which was blocking development. 
</blockquote></details>

But shouldn't it be added back now that development is done? Or is it gener
___
*[toxcore/group_chats.h, line 62 at r4](https://reviewable.io/reviews/toktok/c-toxcore/2269#-N0CXB_UDp7MnG0F_fj_:-N0HXEfC-qTAlDIZHrAU:btdsfzr) ([raw file](https://github.com/toktok/c-toxcore/blob/2904fbdd42c216322c844568aadb319675a8c6af/toxcore/group_chats.h#L62)):*
<details><summary><i>Previously, JFreegman wrote…</i></summary><blockquote>

I'm reluctant to change any of the enum prefixes because we will probably end up changing them all again in the future to satisfy cimple
</blockquote></details>

I see.
___
*[toxcore/group_chats.c, line 71 at r4](https://reviewable.io/reviews/toktok/c-toxcore/2269#-N0C_8rY8_yPGy3IdAt6:-N0HYkK89_pdagzH5Bqn:b-wtggou) ([raw file](https://github.com/toktok/c-toxcore/blob/2904fbdd42c216322c844568aadb319675a8c6af/toxcore/group_chats.c#L71)):*
<details><summary><i>Previously, JFreegman wrote…</i></summary><blockquote>

Done. Added a comment.
</blockquote></details>

Ok, but how did you come up with exactly 8 bytes padding? why is it enough?
___
*[toxcore/group_chats.c, line 1854 at r4](https://reviewable.io/reviews/toktok/c-toxcore/2269#-N0CcpeA2LkXG3ppicTx:-N0HY1tKCn4VxJH7PGfA:b-a0bwtk) ([raw file](https://github.com/toktok/c-toxcore/blob/2904fbdd42c216322c844568aadb319675a8c6af/toxcore/group_chats.c#L1854)):*
<details><summary><i>Previously, JFreegman wrote…</i></summary><blockquote>

Validation won't work if they're sent in the wrong order. I'll add this info to the spec.
</blockquote></details>

Can you also add a comment linking the spec? otherwise this comment is quite confusing to m.
___
*[toxcore/group_chats.c, line 2326 at r4](https://reviewable.io/reviews/toktok/c-toxcore/2269#-N0CdVQf5xPCAdmChA-s:-N0HYGZO-WXXQhZYr-Kz:b-60car2) ([raw file](https://github.com/toktok/c-toxcore/blob/2904fbdd42c216322c844568aadb319675a8c6af/toxcore/group_chats.c#L2326)):*
<details><summary><i>Previously, JFreegman wrote…</i></summary><blockquote>

This is the same style of packet packing/unpacking that's used for all other NGC packets. If we switch to a struct model it should be done uniformly (and should use cmp)
</blockquote></details>

Ok then.
___
*[toxcore/group_chats.c, line 2728 at r4](https://reviewable.io/reviews/toktok/c-toxcore/2269#-N0Ce_K207wsHM2DRVIk:-N0HYPVG12rARp-rXai6:b-d0dcj9) ([raw file](https://github.com/toktok/c-toxcore/blob/2904fbdd42c216322c844568aadb319675a8c6af/toxcore/group_chats.c#L2728)):*
<details><summary><i>Previously, JFreegman wrote…</i></summary><blockquote>

Done. Should say flag.
</blockquote></details>

Makes sense now :)
___
*[toxcore/group_chats.c, line 1753 at r5](https://reviewable.io/reviews/toktok/c-toxcore/2269#-N0HZWoKCy7bEKTkI-2E:-N0HZWoKCy7bEKTkI-2F:b-wyj147) ([raw file](https://github.com/toktok/c-toxcore/blob/4ba058d2f700d2257597eda0fa70bff2e98c0bdc/toxcore/group_chats.c#L1753)):*
> ```C
> }
> 
> non_null() static int get_gc_peer_public_key(const GC_Chat *chat, uint32_t peer_number, uint8_t *public_key);
> ```

Move to the top with the rest? IDK if there's a style guide on where to put prototypes
___
*[toxcore/group_chats.c, line 1960 at r5](https://reviewable.io/reviews/toktok/c-toxcore/2269#-N0HZnT00hu46Fyw3A1u:-N0HZnT00hu46Fyw3A1v:bb7od0r) ([raw file](https://github.com/toktok/c-toxcore/blob/4ba058d2f700d2257597eda0fa70bff2e98c0bdc/toxcore/group_chats.c#L1960)):*
> ```C
> }
> 
> non_null() static void copy_self(const GC_Chat *chat, GC_Peer *peer);
> ```

same
___
*[toxcore/group_chats.c, line 2078 at r5](https://reviewable.io/reviews/toktok/c-toxcore/2269#-N0H_HL_9zb1guUVqXTV:-N0H_HL_9zb1guUVqXTW:bevcmud) ([raw file](https://github.com/toktok/c-toxcore/blob/4ba058d2f700d2257597eda0fa70bff2e98c0bdc/toxcore/group_chats.c#L2078)):*
> ```C
>  */
> non_null()
> static int handle_gc_invite_response(GC_Chat *chat, GC_Connection *gconn)
> ```

not sure if `handle_` means this will be used as a callback with a given signature, but otherwise it could return bool. There are multiple occurences of this
___
*[toxcore/group_chats.c, line 2080 at r5](https://reviewable.io/reviews/toktok/c-toxcore/2269#-N0H_8m89l0jG1KWKEGN:-N0H_8m89l0jG1KWKEGO:b-6tkghc) ([raw file](https://github.com/toktok/c-toxcore/blob/4ba058d2f700d2257597eda0fa70bff2e98c0bdc/toxcore/group_chats.c#L2080)):*
> ```C
> static int handle_gc_invite_response(GC_Chat *chat, GC_Connection *gconn)
> {
>     if (!send_gc_sync_request(chat, gconn, 0xffff)) {
> ```

please define this magic value
___
*[toxcore/group_chats.c, line 3400 at r5](https://reviewable.io/reviews/toktok/c-toxcore/2269#-N0HbsPh8p9I-dVF0mKG:-N0HbsPh8p9I-dVF0mKH:b-ph2eb) ([raw file](https://github.com/toktok/c-toxcore/blob/4ba058d2f700d2257597eda0fa70bff2e98c0bdc/toxcore/group_chats.c#L3400)):*
> ```C
>                           uint16_t length,  void *userdata)
> {
>     /** If this happens malicious behaviour is highly suspect */
> ```

should this really be a doxygen comment?
___
*[toxcore/group_chats.c, line 3635 at r5](https://reviewable.io/reviews/toktok/c-toxcore/2269#-N0HcX9_1RYwOHlVAT2G:-N0HcX9_1RYwOHlVAT2H:btcztmm) ([raw file](https://github.com/toktok/c-toxcore/blob/4ba058d2f700d2257597eda0fa70bff2e98c0bdc/toxcore/group_chats.c#L3635)):*
> ```C
> 
>     // TODO(jfreegman): improbable, but an overflow would break everything
>     if (chat->topic_info.version == UINT32_MAX) {
> ```

break everything sounds bad, something we should do about this?
___
*[toxcore/group_chats.c, line 3755 at r5](https://reviewable.io/reviews/toktok/c-toxcore/2269#-N0HcuiSBPGtM0Ct1kdG:-N0HcuiSBPGtM0Ct1kdH:b-bek1kb) ([raw file](https://github.com/toktok/c-toxcore/blob/4ba058d2f700d2257597eda0fa70bff2e98c0bdc/toxcore/group_chats.c#L3755)):*
> ```C
>         if (gc_get_enc_pk_from_sig_pk(chat, public_enc_key, topic_info->public_sig_key)) {
>             if (sanctions_list_is_observer(&chat->moderation, public_enc_key)) {
>                 LOGGER_DEBUG(chat->log, "Invalid topic signature (sanctioned peeer attempted to change topic)");
> ```

typo `peer`
___
*[toxcore/group_chats.c, line 3856 at r5](https://reviewable.io/reviews/toktok/c-toxcore/2269#-N0HdCRt-NdJgwogKCQk:-N0HdCRt-NdJgwogKCQl:b-6tkghc) ([raw file](https://github.com/toktok/c-toxcore/blob/4ba058d2f700d2257597eda0fa70bff2e98c0bdc/toxcore/group_chats.c#L3856)):*
> ```C
>     }
> 
>     const bool is_response = data [...]

2022-04-23 07:15 UTC, zoff99 commented
@JFreegman @iphydf the ```tox_unlock()``` and ```tox_lock()``` calls are missing for the group callback functions in ```tox.c```

2022-04-23 16:03 UTC, JFreegman reviewed
> *[Reviewable](https://reviewable.io/reviews/toktok/c-toxcore/2269)* status: 2 change requests, 0 of 1 approvals obtained (waiting on @iphydf, @JFreegman, and @sudden6)

___
*[auto_tests/group_topic_test.c, line 106 at r5](https://reviewable.io/reviews/toktok/c-toxcore/2269#-N0HWogd7Qrey7EWzPaq:-N0M-xJT85Nu-Wxiw9LO:b-896fix) ([raw file](https://github.com/toktok/c-toxcore/blob/4ba058d2f700d2257597eda0fa70bff2e98c0bdc/auto_tests/group_topic_test.c#L106)):*
<details><summary><i>Previously, sudden6 wrote…</i></summary><blockquote>

can be simplified to a oneliner now
</blockquote></details>

Done.
___
*[other/analysis/variants.sh, line 4 at r4](https://reviewable.io/reviews/toktok/c-toxcore/2269#-N0CWiHQ1kWgNBTmvBB7:-N0M-ymvE8Fw_YURQfVg:b-1f1e98) ([raw file](https://github.com/toktok/c-toxcore/blob/50094b73851b96081f370318cdbc1b5656722433/other/analysis/variants.sh#L4)):*
<details><summary><i>Previously, sudden6 wrote…</i></summary><blockquote>

But shouldn't it be added back now that development is done? Or is it gener
</blockquote></details>

I don't know. It's not fixed and breaks any CI that uses nacl. @iphydf ?
___
*[toxcore/group_chats.c, line 71 at r4](https://reviewable.io/reviews/toktok/c-toxcore/2269#-N0C_8rY8_yPGy3IdAt6:-N0M06nb6Ve1O18R9WUh:b353jjz) ([raw file](https://github.com/toktok/c-toxcore/blob/2904fbdd42c216322c844568aadb319675a8c6af/toxcore/group_chats.c#L71)):*
<details><summary><i>Previously, sudden6 wrote…</i></summary><blockquote>

Ok, but how did you come up with exactly 8 bytes padding? why is it enough?
</blockquote></details>

I just copied what net crypto does. We could theorize on the best value, but as it stands it's not making anything worse.
___
*[toxcore/group_chats.c, line 1753 at r5](https://reviewable.io/reviews/toktok/c-toxcore/2269#-N0HZWoKCy7bEKTkI-2E:-N0M0QR98p_YAwybDVyJ:b-h4p31g) ([raw file](https://github.com/toktok/c-toxcore/blob/4ba058d2f700d2257597eda0fa70bff2e98c0bdc/toxcore/group_chats.c#L1753)):*
<details><summary><i>Previously, sudden6 wrote…</i></summary><blockquote>

Move to the top with the rest? IDK if there's a style guide on where to put prototypes
</blockquote></details>

Generally if I use the function in a lot of places, I put it at the top. If I just use it in one place, I put it above the function that it's used in. But there are probably instances where that doesn't hold. Is it important either way?
___
*[toxcore/group_chats.c, line 1960 at r5](https://reviewable.io/reviews/toktok/c-toxcore/2269#-N0HZnT00hu46Fyw3A1u:-N0M0nQu4zj9B8HmBaQb:b-896fix) ([raw file](https://github.com/toktok/c-toxcore/blob/4ba058d2f700d2257597eda0fa70bff2e98c0bdc/toxcore/group_chats.c#L1960)):*
<details><summary><i>Previously, sudden6 wrote…</i></summary><blockquote>

same
</blockquote></details>

Done.
___
*[toxcore/group_chats.c, line 2078 at r5](https://reviewable.io/reviews/toktok/c-toxcore/2269#-N0H_HL_9zb1guUVqXTV:-N0M0xA3C4nt8uaBUVgK:b-qwu4k1) ([raw file](https://github.com/toktok/c-toxcore/blob/4ba058d2f700d2257597eda0fa70bff2e98c0bdc/toxcore/group_chats.c#L2078)):*
<details><summary><i>Previously, sudden6 wrote…</i></summary><blockquote>

not sure if `handle_` means this will be used as a callback with a given signature, but otherwise it could return bool. There are multiple occurences of this
</blockquote></details>

It's intentional. There are some instances of handlers that return an int instead of bool because the calling function uses ints to report more descriptive errors from a set of handlers, some of which return more than just two values. I could change it to a bool and then do an explicit conversion to an int in the caller function but that seems like unnecessary complexity to satisfy a semantics rule.
___
*[toxcore/group_chats.c, line 2080 at r5](https://reviewable.io/reviews/toktok/c-toxcore/2269#-N0H_8m89l0jG1KWKEGN:-N0M1mTq0qQZvH7NMORd:b-896fix) ([raw file](https://github.com/toktok/c-toxcore/blob/4ba058d2f700d2257597eda0fa70bff2e98c0bdc/toxcore/group_chats.c#L2080)):*
<details><summary><i>Previously, sudden6 wrote…</i></summary><blockquote>

please define this magic value
</blockquote></details>

Done.
___
*[toxcore/group_chats.c, line 3400 at r5](https://reviewable.io/reviews/toktok/c-toxcore/2269#-N0HbsPh8p9I-dVF0mKG:-N0M2Y7VE6JGdoKYViD_:b-896fix) ([raw file](https://github.com/toktok/c-toxcore/blob/4ba058d2f700d2257597eda0fa70bff2e98c0bdc/toxcore/group_chats.c#L3400)):*
<details><summary><i>Previously, sudden6 wrote…</i></summary><blockquote>

should this really be a doxygen comment?
</blockquote></details>

Done.
___
*[toxcore/group_chats.c, line 3635 at r5](https://reviewable.io/reviews/toktok/c-toxcore/2269#-N0HcX9_1RYwOHlVAT2G:-N0M2dZF8-iLHnHoebd_:b7gwdep) ([raw file](https://github.com/toktok/c-toxcore/blob/4ba058d2f700d2257597eda0fa70bff2e98c0bdc/toxcore/group_chats.c#L3635)):*
<details><summary><i>Previously, sudden6 wrote…</i></summary><blockquote>

break everything sounds bad, something we should do about this?
</blockquote></details>

By "everything" I just meant topic setting/validation. We can't really do anything about it aside from not let it happen afaik. It's very unlikely that the topic will be changed ~4 billion times in a given group.
___
*[toxcore/group_chats.c, line 3755 at r5](https://reviewable.io/reviews/toktok/c-toxcore/2269#-N0HcuiSBPGtM0Ct1kdG:-N0M2z-vD-Gfvdrxje_0:b-896fix) ([raw file](https://github.com/toktok/c-toxcore/blob/4ba058d2f700d2257597eda0fa70bff2e98c0bdc/toxcore/group_chats.c#L3755)):*
<details><summary><i>Previously, sudden6 wrote…</i></summary><blockquote>

typo `peer`
</blockquote></details>

Done.
___
*[toxcore/group_chats.c, line 3856 at r5](https://reviewable.io/reviews/toktok/c-toxcore/2269#-N0HdCRt-NdJgwogKCQk:-N0M3-x898FlWPGZNr5z:b-qbo56p) ([raw file](https://github.com/toktok/c-toxcore/blob/4ba058d2f700d2257597eda0fa70bff2e98c0bdc/toxcore/group_chats.c#L3856)):*
<details><summary><i>Previously, sudden6 wrote…</i></summary><blockquote>

please define this magic value
</blockquote></details>

All of these instances are just booleans being converted to/from ints for the purpose of packet packing. They are already defined as boolean (or zero versus non-zero) in the packet protocol. Since the protocol allows for any non-zero byte to be used as a `true` it doesn't make sense to define them in the code.
___
*[toxcore/group_chats.c, line 3897 at r5](https://reviewable.io/reviews/toktok/c-toxcore/2269#-N0Hez8S0ZDYVZ-hrsyR:-N0M4j5x0JGN0NtSE-Op:b-512cjy) ([raw file](https://github.com/toktok/c-toxcore/blob/4ba058d2f700d2257597eda0fa70bff2e98c0bdc/toxcore/group_chats.c#L3897)):*
<details><summary><i>Previously, sudden6 wrote…</i></summary><blockquote>

`gconn->session_secret_key` should likely be memlocked too, I don't se that `create_gc_session_keypair` is doing it.
</blockquote></details>

It's locked in`peer_add()`
___
*[toxcore/group_chats.c, line 4064 at r5](https://reviewable.io/reviews/toktok/c-toxcore/2269#-N0Hg1cCAPWzGuvneoqC:-N0M4qCZ0X0aitc3LeMW:bzd6zrr) ([raw file](https://github.com/toktok/c-toxcore/blob/4ba058d2f700d2257597eda0fa70bff2e98c0bdc/toxcore/group_chats.c#L4064)):*
<details><summary><i>Previously, sudden6 wrote…</i></summary><blockquote>

please define this magic value
</blockquote></details>

Done. See above.
___
*[toxcore/group_chats.c, line 4102 at r5](https://reviewable.io/reviews/toktok/c-toxcore/2269#-N0Hg9Kx-Nbq74wN-eGB:-N0M4t-H5wcWk0ze56HU:bzd6zrr) ([raw file](https://github.com/toktok/c-toxcore/blob/4ba058d2f700d2257597eda0fa70bff2e98c0bdc/toxcore/group_chats.c#L4102)):*
<details><summary><i>Previously, sudden6 wrote…</i></summary><blockquote>

same
</blockquote></details>

Done. See above.
___
*[toxcore/group_chats.c, line 4245 at r5](https://reviewable.io/reviews/toktok/c-toxcore/2269#-N0HgLudCqTPxgLXMwuU:-N0M4u_e0ZHdBEhumnxZ:buwbz9v) ([raw file](https://github.com/toktok/c-toxcore/blob/4ba058d2f700d2257597eda0fa70bff2e98c0bdc/toxcore/group_chats.c#L4245)):*
<details><summary><i>Previously, sudden6 wrote…</i></summar [...]

2022-04-24 01:45 UTC, sudden6 requested changes
> *[Reviewable](https://reviewable.io/reviews/toktok/c-toxcore/2269)* status: 2 change requests, 0 of 1 approvals obtained (waiting on @iphydf, @JFreegman, and @sudden6)

___
*[auto_tests/group_topic_test.c, line 106 at r5](https://reviewable.io/reviews/toktok/c-toxcore/2269#-N0HWogd7Qrey7EWzPaq:-N0MZlyN7Bb6lvfbQOzC:besg18c) ([raw file](https://github.com/toktok/c-toxcore/blob/4ba058d2f700d2257597eda0fa70bff2e98c0bdc/auto_tests/group_topic_test.c#L106)):*
<details><summary><i>Previously, JFreegman wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Not seeing any change?
___
*[toxcore/group_chats.c, line 71 at r4](https://reviewable.io/reviews/toktok/c-toxcore/2269#-N0C_8rY8_yPGy3IdAt6:-N0MZuDVC8GrBcETW36V:b-x1skow) ([raw file](https://github.com/toktok/c-toxcore/blob/2904fbdd42c216322c844568aadb319675a8c6af/toxcore/group_chats.c#L71)):*
<details><summary><i>Previously, JFreegman wrote…</i></summary><blockquote>

I just copied what net crypto does. We could theorize on the best value, but as it stands it's not making anything worse.
</blockquote></details>

`I just copied what net crypto does` that's the info I was looking for, maybe mention it in the comments that this is same as net_crypto behavior.
___
*[toxcore/group_chats.c, line 1753 at r5](https://reviewable.io/reviews/toktok/c-toxcore/2269#-N0HZWoKCy7bEKTkI-2E:-N0M_8Qw34NcVDBKPS2z:b-e8pls9) ([raw file](https://github.com/toktok/c-toxcore/blob/4ba058d2f700d2257597eda0fa70bff2e98c0bdc/toxcore/group_chats.c#L1753)):*
<details><summary><i>Previously, JFreegman wrote…</i></summary><blockquote>

Generally if I use the function in a lot of places, I put it at the top. If I just use it in one place, I put it above the function that it's used in. But there are probably instances where that doesn't hold. Is it important either way?
</blockquote></details>

Personally I prefer them to be all at the top, but I guess that's not covered by the Toktok style guide so what you're doing is probably alright.
___
*[toxcore/group_chats.c, line 2078 at r5](https://reviewable.io/reviews/toktok/c-toxcore/2269#-N0H_HL_9zb1guUVqXTV:-N0Ma9gV4r7sY4o5L7AQ:b-sbjmu9) ([raw file](https://github.com/toktok/c-toxcore/blob/4ba058d2f700d2257597eda0fa70bff2e98c0bdc/toxcore/group_chats.c#L2078)):*
<details><summary><i>Previously, JFreegman wrote…</i></summary><blockquote>

It's intentional. There are some instances of handlers that return an int instead of bool because the calling function uses ints to report more descriptive errors from a set of handlers, some of which return more than just two values. I could change it to a bool and then do an explicit conversion to an int in the caller function but that seems like unnecessary complexity to satisfy a semantics rule.
</blockquote></details>

Ok for me then.
___
*[toxcore/group_chats.c, line 3635 at r5](https://reviewable.io/reviews/toktok/c-toxcore/2269#-N0HcX9_1RYwOHlVAT2G:-N0Mb-1Z9fpC35ktGHYn:b-y7jzcr) ([raw file](https://github.com/toktok/c-toxcore/blob/4ba058d2f700d2257597eda0fa70bff2e98c0bdc/toxcore/group_chats.c#L3635)):*
<details><summary><i>Previously, JFreegman wrote…</i></summary><blockquote>

By "everything" I just meant topic setting/validation. We can't really do anything about it aside from not let it happen afaik. It's very unlikely that the topic will be changed ~4 billion times in a given group.
</blockquote></details>

Would it be possible to change this to a type of modulo counter, such that you don't have to recreate the group once this limit is reached?


<!-- Sent from Reviewable.io -->

2022-04-24 15:57 UTC, JFreegman reviewed
> *[Reviewable](https://reviewable.io/reviews/toktok/c-toxcore/2269)* status: 2 change requests, 0 of 1 approvals obtained (waiting on @iphydf, @JFreegman, and @sudden6)

___
*[`auto_tests/group_topic_test.c` line 106 at r5](https://reviewable.io/reviews/toktok/c-toxcore/2269#-N0HWogd7Qrey7EWzPaq:-N0RFLPG8OnETMmzHx8L:b4lvnqf) ([raw file](https://github.com/toktok/c-toxcore/blob/4ba058d2f700d2257597eda0fa70bff2e98c0bdc/auto_tests/group_topic_test.c#L106)):*
<details><summary><i>Previously, sudden6 wrote…</i></summary><blockquote>

Not seeing any change?
</blockquote></details>

Should be there, line 110
___
*[`toxcore/group_chats.c` line 71 at r4](https://reviewable.io/reviews/toktok/c-toxcore/2269#-N0C_8rY8_yPGy3IdAt6:-N0RFPkN31FqVI97c0Y_:b-896fix) ([raw file](https://github.com/toktok/c-toxcore/blob/2904fbdd42c216322c844568aadb319675a8c6af/toxcore/group_chats.c#L71)):*
<details><summary><i>Previously, sudden6 wrote…</i></summary><blockquote>

`I just copied what net crypto does` that's the info I was looking for, maybe mention it in the comments that this is same as net_crypto behavior.
</blockquote></details>

Done.
___
*[`toxcore/group_chats.c` line 3635 at r5](https://reviewable.io/reviews/toktok/c-toxcore/2269#-N0HcX9_1RYwOHlVAT2G:-N0RGDyt0nq2JwTSwdwm:b-sxnmrv) ([raw file](https://github.com/toktok/c-toxcore/blob/4ba058d2f700d2257597eda0fa70bff2e98c0bdc/toxcore/group_chats.c#L3635)):*
<details><summary><i>Previously, sudden6 wrote…</i></summary><blockquote>

Would it be possible to change this to a type of modulo counter, such that you don't have to recreate the group once this limit is reached?
</blockquote></details>

The point of the version is to make sure that a peer without sufficient permission doesn't save an old topic packet and send it to the group in the future, thus being able to change the topic when the topic lock is enabled. So if it wraps around, it defeats the purpose.


<!-- Sent from Reviewable.io -->

2022-04-24 16:37 UTC, sudden6 requested changes
> Reviewed 1 of 14 files at r2, 2 of 8 files at r7, 2 of 4 files at r11.
> *[Reviewable](https://reviewable.io/reviews/toktok/c-toxcore/2269)* status: 2 change requests, 0 of 1 approvals obtained (waiting on @iphydf, @JFreegman, and @sudden6)

___
*[`toxcore/group_chats.h` line 148 at r11](https://reviewable.io/reviews/toktok/c-toxcore/2269#-N0RPesoEA5dCzbw0lKz:-N0RPesoEA5dCzbw0lL-:b-890eja) ([raw file](https://github.com/toktok/c-toxcore/blob/54f35a07be1eca7cf6df4bc87aeffb3a238f6f3b/toxcore/group_chats.h#L148)):*
> ```objc
> /** @brief Returns the size of a wrapped/encrypted packet with a plain size of `length`.
>  *
>  * `pakcket_type` should be either NET_PACKET_GC_LOSSY or NET_PACKET_GC_LOSSLESS.
> ```

`packet_type`
___
*[`toxcore/group_chats.c` line 3856 at r5](https://reviewable.io/reviews/toktok/c-toxcore/2269#-N0HdCRt-NdJgwogKCQk:-N0RMdjs9HA8WqtQPRNg:bgcr0vk) ([raw file](https://github.com/toktok/c-toxcore/blob/4ba058d2f700d2257597eda0fa70bff2e98c0bdc/toxcore/group_chats.c#L3856)):*
<details><summary><i>Previously, JFreegman wrote…</i></summary><blockquote>

All of these instances are just booleans being converted to/from ints for the purpose of packet packing. They are already defined as boolean (or zero versus non-zero) in the packet protocol. Since the protocol allows for any non-zero byte to be used as a `true` it doesn't make sense to define them in the code.
</blockquote></details>

I'd still prefer to have this more thoroughly defined. Maybe write using an constant and read using a function that does the proper conversion? Same for the following comments.
___
*[`toxcore/group_chats.c` line 4513 at r5](https://reviewable.io/reviews/toktok/c-toxcore/2269#-N0Hge5l-OAPYAk_uILp:-N0RN44s3Qu5AaU5mo3g:b-dzh61w) ([raw file](https://github.com/toktok/c-toxcore/blob/4ba058d2f700d2257597eda0fa70bff2e98c0bdc/toxcore/group_chats.c#L4513)):*
<details><summary><i>Previously, JFreegman wrote…</i></summary><blockquote>

This one is defined as zero in the protocol. See: https://toktok.ltd/spec.html#topics
</blockquote></details>

as above, I'd still prefer to use named constants for better readability in the code.
___
*[`toxcore/group_chats.c` line 5475 at r5](https://reviewable.io/reviews/toktok/c-toxcore/2269#-N0HjL-K2l86mCQU7MgJ:-N0RNS3F4wIf75NtnPGP:b-32q9xg) ([raw file](https://github.com/toktok/c-toxcore/blob/4ba058d2f700d2257597eda0fa70bff2e98c0bdc/toxcore/group_chats.c#L5475)):*
<details><summary><i>Previously, JFreegman wrote…</i></summary><blockquote>

It's a packet handler and asserts get optimized out in release builds, so I'd rather keep it in.
</blockquote></details>

Maybe mention that this is a defense in depth mechanism in the comment then, otherwise the comment is quite confusing.
___
*[`toxcore/group_chats.c` line 5476 at r5](https://reviewable.io/reviews/toktok/c-toxcore/2269#-N0Hj7up2quEqRISlihR:-N0RNM2sCUmIHhZ0G2G2:b-cgwyhu) ([raw file](https://github.com/toktok/c-toxcore/blob/4ba058d2f700d2257597eda0fa70bff2e98c0bdc/toxcore/group_chats.c#L5476)):*
<details><summary><i>Previously, JFreegman wrote…</i></summary><blockquote>

Done.
</blockquote></details>

still present
___
*[`toxcore/group_chats.c` line 7958 at r5](https://reviewable.io/reviews/toktok/c-toxcore/2269#-N0Hn7KhC7I4UCIacF9-:-N0ROmL36qFjJDlD2vt4:bnokfc3) ([raw file](https://github.com/toktok/c-toxcore/blob/4ba058d2f700d2257597eda0fa70bff2e98c0bdc/toxcore/group_chats.c#L7958)):*
<details><summary><i>Previously, JFreegman wrote…</i></summary><blockquote>

@iphydf has some ideas on how we're going to improve key handling toxcore-wide in the future so that we can make some guarantees about stuff like that.
</blockquote></details>

ok, then. but I'll not be able to thoroughly verify the secret key handling here.
___
*[`toxcore/group_onion_announce.c` line 71 at r5](https://reviewable.io/reviews/toktok/c-toxcore/2269#-N0HpggS-PvgHGcqPk39:-N0RPHRk5HY0AedBrSPb:b2nhll9) ([raw file](https://github.com/toktok/c-toxcore/blob/4ba058d2f700d2257597eda0fa70bff2e98c0bdc/toxcore/group_onion_announce.c#L71)):*
<details><summary><i>Previously, JFreegman wrote…</i></summary><blockquote>

I recall that we decided on not doing this for the time being. It might be part of a core-wide refactor some day.
</blockquote></details>

Ok.


<!-- Sent from Reviewable.io -->

2022-04-24 16:52 UTC, JFreegman reviewed
> *[Reviewable](https://reviewable.io/reviews/toktok/c-toxcore/2269)* status: 2 change requests, 0 of 1 approvals obtained (waiting on @iphydf, @JFreegman, and @sudden6)

___
*[`toxcore/group_chats.h` line 148 at r11](https://reviewable.io/reviews/toktok/c-toxcore/2269#-N0RPesoEA5dCzbw0lKz:-N0RTNxTAyXdy2054CNw:b-896fix) ([raw file](https://github.com/toktok/c-toxcore/blob/54f35a07be1eca7cf6df4bc87aeffb3a238f6f3b/toxcore/group_chats.h#L148)):*
<details><summary><i>Previously, sudden6 wrote…</i></summary><blockquote>

`packet_type`
</blockquote></details>

Done.
___
*[`toxcore/group_chats.c` line 5476 at r5](https://reviewable.io/reviews/toktok/c-toxcore/2269#-N0Hj7up2quEqRISlihR:-N0RTTOL4DYmXEpKcFZz:b-896fix) ([raw file](https://github.com/toktok/c-toxcore/blob/4ba058d2f700d2257597eda0fa70bff2e98c0bdc/toxcore/group_chats.c#L5476)):*
<details><summary><i>Previously, sudden6 wrote…</i></summary><blockquote>

still present
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-04-24 16:53 UTC, sudden6 reviewed
> Reviewed 1 of 3 files at r13.
> *[Reviewable](https://reviewable.io/reviews/toktok/c-toxcore/2269)* status: 2 change requests, 0 of 1 approvals obtained (waiting on @iphydf, @JFreegman, and @sudden6)



<!-- Sent from Reviewable.io -->

2022-04-28 15:46 UTC, JFreegman reviewed
> *[Reviewable](https://reviewable.io/reviews/toktok/c-toxcore/2269)* status: 2 change requests, 0 of 1 approvals obtained (waiting on @iphydf, @JFreegman, and @sudden6)

___
*[`toxcore/group_chats.c` line 1854 at r4](https://reviewable.io/reviews/toktok/c-toxcore/2269#-N0CcpeA2LkXG3ppicTx:-N0kmzl_7OgHEeXJ1Z-5:blvodwz) ([raw file](https://github.com/toktok/c-toxcore/blob/2904fbdd42c216322c844568aadb319675a8c6af/toxcore/group_chats.c#L1854)):*
<details><summary><i>Previously, sudden6 wrote…</i></summary><blockquote>

Can you also add a comment linking the spec? otherwise this comment is quite confusing to m.
</blockquote></details>

Done, and added to spec. https://toktok.ltd/spec.html#sync_request-0xf8
___
*[`toxcore/group_chats.c` line 3856 at r5](https://reviewable.io/reviews/toktok/c-toxcore/2269#-N0HdCRt-NdJgwogKCQk:-N0kq9jC8BL7FbPsKZyz:b-pfrnve) ([raw file](https://github.com/toktok/c-toxcore/blob/4ba058d2f700d2257597eda0fa70bff2e98c0bdc/toxcore/group_chats.c#L3856)):*
<details><summary><i>Previously, sudden6 wrote…</i></summary><blockquote>

I'd still prefer to have this more thoroughly defined. Maybe write using an constant and read using a function that does the proper conversion? Same for the following comments.
</blockquote></details>

Since this occurs in various different packets this would require me to either re-define a general boolean type, or have multiple packet-specific boolean types. I'm not sure what purpose that would serve. What specifically do you find ambiguous or confusing, keeping the spec in mind? (I just updated the spec to further clarify).


<!-- Sent from Reviewable.io -->

2022-04-29 06:50 UTC, zoff99 commented on toxcore/Messenger.c
> +
can we write the next few lines a bit better?
lots of "magic" numbers are repeated with copy and paste
```2 + GC_JOIN_DATA_LENGTH```
```data + 2```
```data_length - 2```

2022-04-29 14:25 UTC, JFreegman reviewed
> *[Reviewable](https://reviewable.io/reviews/toktok/c-toxcore/2269)* status: 2 change requests, 0 of 1 approvals obtained (waiting on @iphydf, @sudden6, and @zoff99)

___
*[`toxcore/group_chats.c` line 4513 at r5](https://reviewable.io/reviews/toktok/c-toxcore/2269#-N0Hge5l-OAPYAk_uILp:-N0pgme6D3yfAN5oV-qT:b-896fix) ([raw file](https://github.com/toktok/c-toxcore/blob/4ba058d2f700d2257597eda0fa70bff2e98c0bdc/toxcore/group_chats.c#L4513)):*
<details><summary><i>Previously, sudden6 wrote…</i></summary><blockquote>

as above, I'd still prefer to use named constants for better readability in the code.
</blockquote></details>

Done.
___
*[`toxcore/group_chats.c` line 5475 at r5](https://reviewable.io/reviews/toktok/c-toxcore/2269#-N0HjL-K2l86mCQU7MgJ:-N0pfpEW0tfWjF1S5JqV:b-896fix) ([raw file](https://github.com/toktok/c-toxcore/blob/4ba058d2f700d2257597eda0fa70bff2e98c0bdc/toxcore/group_chats.c#L5475)):*
<details><summary><i>Previously, sudden6 wrote…</i></summary><blockquote>

Maybe mention that this is a defense in depth mechanism in the comment then, otherwise the comment is quite confusing.
</blockquote></details>

Done.
___
*[`toxcore/Messenger.c` line 2334 at r14](https://reviewable.io/reviews/toktok/c-toxcore/2269#-N-8ftbu5YEBl1-OH0DV-r14-2334:-N0pafZc0TlZcqft2WTR:b-896fix) ([raw file](https://github.com/toktok/c-toxcore/blob/545afc7f4df9a4ce45390694c4c6ff9685a172e4/toxcore/Messenger.c#L2334)):*
<details><summary><i>Previously, zoff99 (Zoff) wrote…</i></summary><blockquote>

can we write the next few lines a bit better?
lots of "magic" numbers are repeated with copy and paste
```2 + GC_JOIN_DATA_LENGTH```
```data + 2```
```data_length - 2```
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-04-30 07:55 UTC, sudden6 requested changes
> Reviewed 2 of 12 files at r5, 1 of 4 files at r6, 2 of 8 files at r7, 1 of 5 files at r8, 1 of 4 files at r11, 3 of 5 files at r15, 1 of 1 files at r16, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/toktok/c-toxcore/2269)* status: 2 change requests, 0 of 1 approvals obtained (waiting on @iphydf, @JFreegman, and @zoff99)

___
*[`toxcore/group_announce.c` line 189 at r16](https://reviewable.io/reviews/toktok/c-toxcore/2269#-N0tRoBWDPqblEaFU29v:-N0tRoBWDPqblEaFU29w:bg7mzzj) ([raw file](https://github.com/toktok/c-toxcore/blob/7f9a4211c417801522a54d7de880e7f73dfb8f10/toxcore/group_announce.c#L189)):*
> ```C
>     offset += ENC_PUBLIC_KEY_SIZE;
> 
>     announce->ip_port_is_set = data[offset] > 0;
> ```

net_unpack_bool?
___
*[`toxcore/group_chats.c` line 3635 at r5](https://reviewable.io/reviews/toktok/c-toxcore/2269#-N0HcX9_1RYwOHlVAT2G:-N0qW8oSCIIuU2RzA4wY:b-xwwjg2) ([raw file](https://github.com/toktok/c-toxcore/blob/4ba058d2f700d2257597eda0fa70bff2e98c0bdc/toxcore/group_chats.c#L3635)):*
<details><summary><i>Previously, JFreegman wrote…</i></summary><blockquote>

The point of the version is to make sure that a peer without sufficient permission doesn't save an old topic packet and send it to the group in the future, thus being able to change the topic when the topic lock is enabled. So if it wraps around, it defeats the purpose.
</blockquote></details>

Ok, I guess malicious topic setters with sufficient permisions are then outside the scope of this?
___
*[`toxcore/group_chats.c` line 5555 at r5](https://reviewable.io/reviews/toktok/c-toxcore/2269#-N0HjbJ8CTyDl9yIAfiw:-N0tSGZCEBVOsJ8HDdDu:b-anpyr7) ([raw file](https://github.com/toktok/c-toxcore/blob/4ba058d2f700d2257597eda0fa70bff2e98c0bdc/toxcore/group_chats.c#L5555)):*
<details><summary><i>Previously, JFreegman wrote…</i></summary><blockquote>

Done. Same as above.
</blockquote></details>

I think the same comment as above should be added.


<!-- Sent from Reviewable.io -->

2022-05-01 14:52 UTC, JFreegman reviewed
> *[Reviewable](https://reviewable.io/reviews/toktok/c-toxcore/2269)* status: 2 change requests, 0 of 1 approvals obtained (waiting on @iphydf, @sudden6, and @zoff99)

___
*[`toxcore/group_announce.c` line 189 at r16](https://reviewable.io/reviews/toktok/c-toxcore/2269#-N0tRoBWDPqblEaFU29v:-N1-4bGkACoaUXMXsSim:b-896fix) ([raw file](https://github.com/toktok/c-toxcore/blob/7f9a4211c417801522a54d7de880e7f73dfb8f10/toxcore/group_announce.c#L189)):*
<details><summary><i>Previously, sudden6 wrote…</i></summary><blockquote>

net_unpack_bool?
</blockquote></details>

Done.
___
*[`toxcore/group_chats.c` line 3635 at r5](https://reviewable.io/reviews/toktok/c-toxcore/2269#-N0HcX9_1RYwOHlVAT2G:-N1-4cPj5OLOVYGPRkkN:bkq129e) ([raw file](https://github.com/toktok/c-toxcore/blob/4ba058d2f700d2257597eda0fa70bff2e98c0bdc/toxcore/group_chats.c#L3635)):*
<details><summary><i>Previously, sudden6 wrote…</i></summary><blockquote>

Ok, I guess malicious topic setters with sufficient permisions are then outside the scope of this?
</blockquote></details>

Yes, malicious moderators remain a potential problem.
___
*[`toxcore/group_chats.c` line 5555 at r5](https://reviewable.io/reviews/toktok/c-toxcore/2269#-N0HjbJ8CTyDl9yIAfiw:-N1-57T74RYfaTAie7w4:b-896fix) ([raw file](https://github.com/toktok/c-toxcore/blob/4ba058d2f700d2257597eda0fa70bff2e98c0bdc/toxcore/group_chats.c#L5555)):*
<details><summary><i>Previously, sudden6 wrote…</i></summary><blockquote>

I think the same comment as above should be added.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-05-01 17:43 UTC, sudden6 reviewed
> *[Reviewable](https://reviewable.io/reviews/toktok/c-toxcore/2269)* status: 2 change requests, 0 of 1 approvals obtained (waiting on @iphydf and @zoff99)

___
*[`toxcore/group_chats.c` line 3635 at r5](https://reviewable.io/reviews/toktok/c-toxcore/2269#-N0HcX9_1RYwOHlVAT2G:-N1-hUtP3lxtRAyOO-fD:bax2dfw) ([raw file](https://github.com/toktok/c-toxcore/blob/4ba058d2f700d2257597eda0fa70bff2e98c0bdc/toxcore/group_chats.c#L3635)):*
<details><summary><i>Previously, JFreegman wrote…</i></summary><blockquote>

Yes, malicious moderators remain a potential problem.
</blockquote></details>

Ok, maybe document which roles can do which attacks on the group. I have not seen something in the spec. I think it will avoid many further discussions about security.


<!-- Sent from Reviewable.io -->

2022-05-03 19:58 UTC, sudden6 requested changes
> Reviewed 1 of 5 files at r8, 1 of 2 files at r9, 3 of 4 files at r17, 1 of 1 files at r18, 2 of 2 files at r19, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/toktok/c-toxcore/2269)* status: 2 change requests, 0 of 1 approvals obtained (waiting on @iphydf, @JFreegman, and @zoff99)

___
*[`toxcore/Messenger.c` line 3545 at r19](https://reviewable.io/reviews/toktok/c-toxcore/2269#-N1AUDxECF1vZniPA4Ea:-N1AUDxECF1vZniPA4Eb:b9eqdvj) ([raw file](https://github.com/toktok/c-toxcore/blob/f15e46acdc50d58bf664797a8429148e263db64e/toxcore/Messenger.c#L3545)):*
> ```C
>         kill_net_crypto(m->net_crypto);
>         kill_dht(m->dht);
>         kill_networking(m->net);
> ```

This change looks strange, how can lower layers be killed before higher layers? If this change is sane, update the other cleanup sections too.


<!-- Sent from Reviewable.io -->

2022-05-03 20:24 UTC, JFreegman reviewed
> *[Reviewable](https://reviewable.io/reviews/toktok/c-toxcore/2269)* status: 2 change requests, 0 of 1 approvals obtained (waiting on @iphydf, @sudden6, and @zoff99)

___
*[`toxcore/Messenger.c` line 3545 at r19](https://reviewable.io/reviews/toktok/c-toxcore/2269#-N1AUDxECF1vZniPA4Ea:-N1AZeci7H_nQN0yRP7f:bkxg2f) ([raw file](https://github.com/toktok/c-toxcore/blob/f15e46acdc50d58bf664797a8429148e263db64e/toxcore/Messenger.c#L3545)):*
<details><summary><i>Previously, sudden6 wrote…</i></summary><blockquote>

This change looks strange, how can lower layers be killed before higher layers? If this change is sane, update the other cleanup sections too.
</blockquote></details>

This change fixed a use after free bug caused by an incorrect cleanup order. The unwind order in that ifdef block is now the same as everywhere else in that function (actually I just noticed it's still wrong in one other spot, which is now fixed).


<!-- Sent from Reviewable.io -->

2022-05-04 21:43 UTC, sudden6 reviewed
> *[Reviewable](https://reviewable.io/reviews/toktok/c-toxcore/2269)* status: 2 change requests, 0 of 1 approvals obtained (waiting on @iphydf and @zoff99)

___
*[`toxcore/Messenger.c` line 3545 at r19](https://reviewable.io/reviews/toktok/c-toxcore/2269#-N1AUDxECF1vZniPA4Ea:-N1G0RlaAEHWb9DMuPmE:b-q6c3xx) ([raw file](https://github.com/toktok/c-toxcore/blob/f15e46acdc50d58bf664797a8429148e263db64e/toxcore/Messenger.c#L3545)):*
<details><summary><i>Previously, JFreegman wrote…</i></summary><blockquote>

This change fixed a use after free bug caused by an incorrect cleanup order. The unwind order in that ifdef block is now the same as everywhere else in that function (actually I just noticed it's still wrong in one other spot, which is now fixed).
</blockquote></details>

Ok, coincidentally this other spot was what I took as reference


<!-- Sent from Reviewable.io -->

2022-05-05 20:24 UTC, Green-Sky commented on toxcore/tox.h
> + * @param length The length of the packet data byte array.
The api does not say how large it can be.

2022-05-06 16:13 UTC, JFreegman reviewed
> *[Reviewable](https://reviewable.io/reviews/toktok/c-toxcore/2269)* status: 2 change requests, 0 of 1 approvals obtained (waiting on @Green-Sky, @iphydf, and @zoff99)

___
*[`toxcore/tox.h` line 4515 at r20](https://reviewable.io/reviews/toktok/c-toxcore/2269#-N-8ftbu5YEBl1-OH0Dl-r20-4515:-N1P8LXa7EAD4IZN9KoI:b-896fix) ([raw file](https://github.com/toktok/c-toxcore/blob/0d3167a4057da6f818e5ff204bcf51116edf2ece/toxcore/tox.h#L4515)):*
<details><summary><i>Previously, Green-Sky (Erik Scholz) wrote…</i></summary><blockquote>

The api does not say how large it can be.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-05-06 21:42 UTC, Green-Sky requested changes

2022-05-06 21:42 UTC, Green-Sky commented on toxcore/tox.h
> + * The message length may not exceed TOX_MAX_CUSTOM_PACKET_SIZE. Larger packets
Thats probably how it's intended, but right now it checks for `MAX_GC_MESSAGE_SIZE`, which is 1 byte shorter.

2022-05-06 23:23 UTC, JFreegman reviewed
> *[Reviewable](https://reviewable.io/reviews/toktok/c-toxcore/2269)* status: 2 change requests, 0 of 1 approvals obtained (waiting on @Green-Sky, @iphydf, and @zoff99)

___
*[`toxcore/tox.h` line 4512 at r21](https://reviewable.io/reviews/toktok/c-toxcore/2269#-N-8ftbu5YEBl1-OH0Dl-r21-4512:-N1Qflrv9zG_lM0KDga5:b-376vyb) ([raw file](https://github.com/toktok/c-toxcore/blob/b49c6bde7c2a6f24127fcd6af14e264d0296f2ca/toxcore/tox.h#L4512)):*
<details><summary><i>Previously, Green-Sky (Erik Scholz) wrote…</i></summary><blockquote>

That's probably how it's intended, but right now it checks for `MAX_GC_MESSAGE_SIZE`, which is 1 byte shorter.
</blockquote></details>

Done. Good catch.


<!-- Sent from Reviewable.io -->

2022-05-16 21:34 UTC, Green-Sky commented on toxcore/group_pack.c
> +    bin_pack_bool(bp, chat->connection_state == CS_DISCONNECTED);
missing `// 1`
not sure if that's important

2022-05-16 21:36 UTC, Green-Sky commented on toxcore/group_pack.c
> +    bin_pack_array(bp, 2);
array of size 2 and you fill in either 0 or 2

2022-05-16 21:39 UTC, Green-Sky commented on toxcore/group_pack.c
> +    mod_list_pack(&chat->moderation, packed_mod_list);
why binary pack if we could use an msgpack array?

2022-05-16 22:35 UTC, JFreegman reviewed
> *[Reviewable](https://reviewable.io/reviews/toktok/c-toxcore/2269)* status: 2 change requests, 0 of 1 approvals obtained (waiting on @Green-Sky, @iphydf, and @zoff99)

___
*[`toxcore/group_pack.c` line 270 at r24](https://reviewable.io/reviews/toktok/c-toxcore/2269#-N-8ftbu5YEBl1-OH0E4-r24-270:-N2DxAdi4taNc8Bv2Y5m:bs7wumx) ([raw file](https://github.com/toktok/c-toxcore/blob/d57ebf34fdf42b9851858bf75eb2a06300868937/toxcore/group_pack.c#L270)):*
<details><summary><i>Previously, Green-Sky (Erik Scholz) wrote…</i></summary><blockquote>

missing `// 1`
not sure if that's important 
</blockquote></details>

Done. 
___
*[`toxcore/group_pack.c` line 308 at r24](https://reviewable.io/reviews/toktok/c-toxcore/2269#-N-8ftbu5YEBl1-OH0E4-r24-308:-N2DxKJP7kB1l43FVxEq:b255596) ([raw file](https://github.com/toktok/c-toxcore/blob/d57ebf34fdf42b9851858bf75eb2a06300868937/toxcore/group_pack.c#L308)):*
<details><summary><i>Previously, Green-Sky (Erik Scholz) wrote…</i></summary><blockquote>

array of size 2 and you fill in either 1 or 2, not sure this causes issues
</blockquote></details>

The size 1 case means there are 0 mods so we skip the second (empty) array member when unpacking.
___
*[`toxcore/group_pack.c` line 328 at r24](https://reviewable.io/reviews/toktok/c-toxcore/2269#-N-8ftbu5YEBl1-OH0E4-r24-328:-N2Dzk9O9GOJyXfVux_w:b7a75c0) ([raw file](https://github.com/toktok/c-toxcore/blob/d57ebf34fdf42b9851858bf75eb2a06300868937/toxcore/group_pack.c#L328)):*
<details><summary><i>Previously, Green-Sky (Erik Scholz) wrote…</i></summary><blockquote>

why binary pack if we could use an msgpack array?
</blockquote></details>

We don't use msgpack for anything outside of the save file. I believe that code is going to be auto-generated in the future, because doing it by hand would be extremely tedious.


<!-- Sent from Reviewable.io -->

2022-05-16 23:04 UTC, Green-Sky reviewed
> *[Reviewable](https://reviewable.io/reviews/toktok/c-toxcore/2269)* status: 2 change requests, 0 of 1 approvals obtained (waiting on @iphydf, @JFreegman, and @zoff99)

___
*[`toxcore/group_pack.c` line 308 at r24](https://reviewable.io/reviews/toktok/c-toxcore/2269#-N-8ftbu5YEBl1-OH0E4-r24-308:-N2E4OWw6_-eESRLoGd3:bpz9n3y) ([raw file](https://github.com/toktok/c-toxcore/blob/d57ebf34fdf42b9851858bf75eb2a06300868937/toxcore/group_pack.c#L308)):*
<details><summary><i>Previously, JFreegman wrote…</i></summary><blockquote>

The size 1 case means there are 0 mods so we skip the second (empty) array member when unpacking.
</blockquote></details>

I do really think that writing the wrong number of elements causes issues in msgpack. Following values, in this case 1, will be assumes to be part of the array. I suggest writing a nil value.


<!-- Sent from Reviewable.io -->

2022-05-17 00:50 UTC, JFreegman reviewed
> *[Reviewable](https://reviewable.io/reviews/toktok/c-toxcore/2269)* status: 2 change requests, 0 of 1 approvals obtained (waiting on @Green-Sky, @iphydf, and @zoff99)

___
*[`toxcore/group_pack.c` line 308 at r24](https://reviewable.io/reviews/toktok/c-toxcore/2269#-N-8ftbu5YEBl1-OH0E4-r24-308:-N2EOvOz9lTmu0xwSeNw:bjje6du) ([raw file](https://github.com/toktok/c-toxcore/blob/d57ebf34fdf42b9851858bf75eb2a06300868937/toxcore/group_pack.c#L308)):*
<details><summary><i>Previously, Green-Sky (Erik Scholz) wrote…</i></summary><blockquote>

I do really think that writing the wrong number of elements causes issues in msgpack. Following values, in this case 1, will be assumes to be part of the array. I suggest writing a nil value.
</blockquote></details>

If it caused issues it would produce an error when you tried to load a group with no mods since that would change the offset for the rest of the save file.


<!-- Sent from Reviewable.io -->

2022-05-17 12:51 UTC, Green-Sky commented
*[`toxcore/group_pack.c` line 308 at r24](https://reviewable.io/reviews/toktok/c-toxcore/2269#-N-8ftbu5YEBl1-OH0E4-r24-308:-N2H1Wmp8-9H8Nyp0WbK:bh30n3p) ([raw file](https://github.com/toktok/c-toxcore/blob/d57ebf34fdf42b9851858bf75eb2a06300868937/toxcore/group_pack.c#L308)):*
<details><summary><i>Previously, JFreegman wrote…</i></summary><blockquote>

If it caused issues it would produce an error when you tried to load a group with no mods since that would change the offset for the rest of the save file.
</blockquote></details>

In any case it still means we produce non spec conforming msgpack.
cmp works on token level, so it does not create a form of hierarchy, which makes the current code able to work, but no one else can parse this correctly.


<!-- Sent from Reviewable.io -->

2022-05-17 13:56 UTC, JFreegman reviewed
> *[Reviewable](https://reviewable.io/reviews/toktok/c-toxcore/2269)* status: 2 change requests, 0 of 1 approvals obtained (waiting on @Green-Sky, @iphydf, and @zoff99)

___
*[`toxcore/group_pack.c` line 308 at r24](https://reviewable.io/reviews/toktok/c-toxcore/2269#-N-8ftbu5YEBl1-OH0E4-r24-308:-N2HIc7P6a5cauws3B5Y:b-896fix) ([raw file](https://github.com/toktok/c-toxcore/blob/d57ebf34fdf42b9851858bf75eb2a06300868937/toxcore/group_pack.c#L308)):*
<details><summary><i>Previously, Green-Sky (Erik Scholz) wrote…</i></summary><blockquote>

In any case it still means we produce non spec conforming msgpack.
cmp works on token level, so it does not create a form of hierarchy, which makes the current code able to work, but no one else can parse this correctly.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-05-18 14:43 UTC, Green-Sky reviewed
> *[Reviewable](https://reviewable.io/reviews/toktok/c-toxcore/2269)* status: 2 change requests, 0 of 1 approvals obtained (waiting on @iphydf, @JFreegman, and @zoff99)

___
*[`toxcore/tox.h` line 4378 at r25](https://reviewable.io/reviews/toktok/c-toxcore/2269#-N2M_sK0E8CN5KK9D_4t:-N2M_sK1AMj8QFMVTexm:b-rk0sgg) ([raw file](https://github.com/toktok/c-toxcore/blob/8c8b32176785962e7d74449adbc12dba902e84db/toxcore/tox.h#L4378)):*
> ```objc
>  * queue.
>  *
>  * The message length may not exceed TOX_MAX_MESSAGE_LENGTH. Larger messages
> ```

It says TOX_MAX_MESSAGE_LENGTH here, while in fact it checks against MAX_GC_MESSAGE_SIZE.
same for the other send functions.


<!-- Sent from Reviewable.io -->

2022-05-18 14:44 UTC, Green-Sky commented
*[`toxcore/tox.h` line 4378 at r25](https://reviewable.io/reviews/toktok/c-toxcore/2269#-N2M_sK0E8CN5KK9D_4t:-N2MbxLn1kMrFCoi4Q8o:b-kyrscz) ([raw file](https://github.com/toktok/c-toxcore/blob/8c8b32176785962e7d74449adbc12dba902e84db/toxcore/tox.h#L4378)):*
<details><summary><i>Previously, Green-Sky (Erik Scholz) wrote…</i></summary><blockquote>

It says TOX_MAX_MESSAGE_LENGTH here, while in fact it checks against MAX_GC_MESSAGE_SIZE.
same for the other send functions.
</blockquote></details>

Ignore the suggestion, idk what happened there.


<!-- Sent from Reviewable.io -->

2022-05-22 20:38 UTC, Green-Sky reviewed
> *[Reviewable](https://reviewable.io/reviews/toktok/c-toxcore/2269)* status: 2 change requests, 0 of 1 approvals obtained (waiting on @iphydf, @JFreegman, and @zoff99)

___
*[`auto_tests/group_message_test.c` line 382 at r25](https://reviewable.io/reviews/toktok/c-toxcore/2269#-N2hU8b90jFbMPP0fX8N:-N2hU8b90jFbMPP0fX8O:b-hzsltr) ([raw file](https://github.com/toktok/c-toxcore/blob/74171779c4c1f6ed91764771df3ca1edd7cdf8e8/auto_tests/group_message_test.c#L382)):*
> ```C
>     // Make sure we're still connected to each friend
>     Tox_Connection conn_1 = tox_friend_get_connection_status(tox0, 0, nullptr);
>     Tox_Connection conn_2 = tox_friend_get_connection_status(tox0, 0, nullptr);
> ```

i think this should be tox1, testing for the same value makes no sense.



_Code quote:_
```C
tox0
```


<!-- Sent from Reviewable.io -->

2022-05-22 22:10 UTC, JFreegman reviewed
> *[Reviewable](https://reviewable.io/reviews/toktok/c-toxcore/2269)* status: 2 change requests, 0 of 1 approvals obtained (waiting on @Green-Sky, @iphydf, and @zoff99)

___
*[`auto_tests/group_message_test.c` line 382 at r25](https://reviewable.io/reviews/toktok/c-toxcore/2269#-N2hU8b90jFbMPP0fX8N:-N2hoW696vKqog_Cn_Zp:b-896fix) ([raw file](https://github.com/toktok/c-toxcore/blob/74171779c4c1f6ed91764771df3ca1edd7cdf8e8/auto_tests/group_message_test.c#L382)):*
<details><summary><i>Previously, Green-Sky (Erik Scholz) wrote…</i></summary><blockquote>

i think this should be tox1, testing for the same value makes no sense.
</blockquote></details>

Done.
___
*[`toxcore/tox.h` line 4378 at r25](https://reviewable.io/reviews/toktok/c-toxcore/2269#-N2M_sK0E8CN5KK9D_4t:-N2hoYozCjMhU_izGk2b:b-896fix) ([raw file](https://github.com/toktok/c-toxcore/blob/74171779c4c1f6ed91764771df3ca1edd7cdf8e8/toxcore/tox.h#L4378)):*
<details><summary><i>Previously, Green-Sky (Erik Scholz) wrote…</i></summary><blockquote>

Ignore the suggestion, idk what happened there.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-05-23 19:53 UTC, sudden6 reviewed
> Reviewed 5 of 8 files at r21, 2 of 4 files at r23, 1 of 1 files at r24, 5 of 5 files at r25, 1 of 1 files at r26, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/toktok/c-toxcore/2269)* status: 2 change requests, 0 of 1 approvals obtained (waiting on @Green-Sky, @iphydf, and @zoff99)



<!-- Sent from Reviewable.io -->

2022-06-16 15:56 UTC, sudden6 approved these changes
<img class="emoji" title=":lgtm_strong:" alt=":lgtm_strong:" align="absmiddle" src="https://reviewable.io/lgtm_strong.png" height="20" width="61"/> Did another round of review, found nothing which should prevent a merge. As I said already I'm not happy with the plaintext passwords (Details: https://github.com/JFreegman/toxcore/pull/27), but this shouldn't block the initial merge.

> Reviewed 7 of 10 files at r27, 13 of 13 files at r28, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/toktok/c-toxcore/2269#-:-N4hCQsJARYFaNd_eGVD:buykmx0)* status: :shipit: complete! 1 change requests, 1 of 1 approvals obtained (waiting on @Green-Sky, @iphydf, and @zoff99)



<!-- Sent from Reviewable.io -->

2022-07-07 16:11 UTC, Green-Sky reviewed
> Reviewed 1 of 4 files at r29, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/toktok/c-toxcore/2269)* status: :shipit: complete! 1 change requests, 1 of 1 approvals obtained (waiting on @iphydf and @zoff99)



<!-- Sent from Reviewable.io -->

2022-09-22 14:46 UTC, iphydf approved these changes
More work needs to be done on this, but the core code paths LGTM. We'll iterate on it after merge.

2022-09-22 17:25 UTC, merged