fix: DHTBootstrap should always respond to version packets with toxcore version
TokTok/c-toxcore pull request #2354
Opened 2022-10-16 23:05 UTC by Tha14

The current implementation does not allow responding to bootstrap node packets which results in some of the nodes in nodes.tox.chat to not have a version. This also means that we do not know which of those nodes are actually up-to-date and which are not, making things complicated when it comes to contacting the server owners.

2022-10-17 00:54 UTC, nurupo commented
I'd say that it's good that it reports "1" as the version. While DHTBootstrap is fine for local testing purposes, we don't want people use DHTBootstrap for hosting real bootstrap nodes, as it doesn't even offer TCP relay server service. With the version being "1" it's easy to detect someone running DHTBootstrap whenever someone submits a node to nodes.tox.chat and ask them to switch to using tox-bootstrapd instead, as that is what we want everyone to run.

2022-10-17 00:57 UTC, nurupo commented
Oh, I see it does support the relay server now. I guess it has been a while since I have looked into DHTBootstrap's code.

2022-10-17 01:05 UTC, Tha14 commented
@nurupo I have people asking me frequently on how to host the bootstrap node on windows. I'd assume we can support the windows version since it works properly with the correct arguments passed. And yes, it does support all the basic stuff now. I'm writing a doc for toxcore on the proper steps to take in order to setup a bootstrap node and telling people that they can't use windows is a bit weird. If you think there is no reason to do any of it then let me know.

2022-10-17 01:27 UTC, nurupo commented
Yep, the only reason to use DHTBootstrap is either for testing or if you are on Windows, as tox-bootstrapd is UNIX-only.  I wonder if there is a similar issue with the maximum number of sockets open on Windows that tox-bootstrapd resolves by increasing the file descriptor limit.

>I'm writing a doc for toxcore on the proper steps to take in order to setup a bootstrap node

Something like this? https://wiki.tox.chat/users/runningnodes

Also, note that [there is already a document describing how to setup tox-bootstrapd](https://github.com/TokTok/c-toxcore/blob/master/other/bootstrap_daemon/README.md), so just pointing to that document should be enough, no need to duplicate the same information in multiple places that might get out of sync over time.

2022-10-17 01:44 UTC, nurupo commented
*[`other/DHT_bootstrap.c` line 161 at r1](https://reviewable.io/reviews/toktok/c-toxcore/2354#-NEY_1h51QKFYIVfMxuL:-NEY_1h62e2XBiif1E82:b-rt3zn5) ([raw file](https://github.com/toktok/c-toxcore/blob/92d3e07d10c19f7bdafa8d1b08234fd43f9b729e/other/DHT_bootstrap.c#L161)):*
> ```C
> 
> #ifdef DHT_NODE_EXTRA_PACKETS
>     bootstrap_set_callbacks(dht_get_net(dht), (uint32_t)DAEMON_VERSION_NUMBER, (const uint8_t *) motd, strlen(motd));
> ```

Should be `strlen(motd)+1`, so that we also transmit the null terminator. `sizeof()` that was here before returned the entire size of the string, including the null terminator, while `strlen()` returns one less,as it doesn't count the null terminator.


<!-- Sent from Reviewable.io -->

2022-10-17 13:00 UTC, Green-Sky commented
> I wonder if there is a similar issue with the maximum number of sockets open on Windows that tox-bootstrapd resolves by increasing the file descriptor limit. DHTBootstrap is not very battle-tested, especially on Windows, we treated it mostly as a toy bootstrap node for testing purposes, so I wouldn't be surprised if there are issues like these that pop up.

excerpt form stackoverflow:
> However for a single process that uses the default C run-time libraries then the default limit is 512

this means yes, you can only serve 512 simultaneously. or worse, with the "handshake done, no data sent" /attack/ it would be 512-256=256

2022-10-23 08:33 UTC, nurupo commented
Just to reiterate, I'm not opposed to this PR, it's blocked only by this off-by-one error and GitHub checks / CI build failures. Well, it is not technically an error, as sending a 0 length string should be allowed, it's that everything: DHTBootstrap and tox-bootstrapd, always sent a 1-length null string for an empty string, so I'm just wary of unnecessary breaking anything that might rely on this behavior when reading the packet.

2022-10-28 23:06 UTC, emdee-is commented
Tha can you fix https://github.com/TokTok/c-toxcore/issues/2330 while you're in there; only a couple of lines in the README (not INSTALL). Thanks.

2023-11-12 06:37 UTC, iphydf requested changes

2023-11-12 06:37 UTC, iphydf commented on other/DHT_bootstrap.c
> +#include "./bootstrap_daemon/src/global.h"
This creates a new dependency. You'll need to add it to the BUILD.bazel file.

2023-11-12 07:04 UTC, nurupo approved these changes
> Reviewed 1 of 1 files at r1, 1 of 1 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/toktok/c-toxcore/2354)* status: :shipit: complete! 1 change requests, 1 of 1 approvals obtained (waiting on @Tha14)



<!-- Sent from Reviewable.io -->

2023-11-12 21:10 UTC, iphydf approved these changes
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/toktok/c-toxcore/2354)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @Tha14)



<!-- Sent from Reviewable.io -->

2023-11-13 16:49 UTC, merged