fix: actually give the larger incoming NGC custom packets via API to the client
TokTok/c-toxcore pull request #2441
Opened 2023-12-01 12:59 UTC by zoff99

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/c-toxcore/2441)

2023-12-01 13:03 UTC, Green-Sky commented on toxcore/group_chats.c
> +typedef enum Group_CustomPkts_Direction {
I dont think we need an whole enum for 2 states.

2023-12-01 15:47 UTC, JFreegman requested changes
Can you give a description for why this fix is necessary?

2023-12-01 15:47 UTC, JFreegman commented on toxcore/group_chats.c
> +typedef enum Group_CustomPkts_Direction {
Why `Pkts` and not just `Packets`?

2023-12-01 15:47 UTC, JFreegman commented on toxcore/group_chats.c
> +    GC_CUSTOMPKTS_SENDING      = (1 << 0), // 1
Why are we using bitmasks? There will only ever be two possibilities and never at the same time. I don't mind an enum but the values shouldn't be bit set.

2023-12-01 15:47 UTC, JFreegman commented on toxcore/group_chats.c
> +
Remove double empty lines

2023-12-01 15:47 UTC, JFreegman commented on toxcore/group_chats.c
> +static bool custom_gc_packet_length_is_valid(uint16_t length, bool lossless, Group_CustomPkts_Direction pkt_direction)
This whole function should be rewritten with less nesting.

2024-01-10 18:49 UTC, zoff99 commented
i think this one is obsolete now in favor of #2535

2024-01-10 18:50 UTC, closed without merging