cleanup: Add dynamically derived array sizes to the API.
TokTok/c-toxcore pull request #2525
Opened 2024-01-05 21:06 UTC by iphydf

2024-01-05 22:21 UTC, nurupo requested changes

2024-01-05 22:21 UTC, nurupo commented on toxav/toxav.h
> +        const uint8_t v[/*! max(width/2, abs(ustride)) * (height/2) */],
`ustride` for the size of `v[]` too?

2024-01-05 22:23 UTC, iphydf commented on toxav/toxav.h
> +        const uint8_t v[/*! max(width/2, abs(ustride)) * (height/2) */],
Good catch, thanks!

2024-01-05 22:23 UTC, nurupo commented
Ok, will refrain from looking at it for now since it's a draft (didn't notice at first).

2024-01-07 02:03 UTC, iphydf commented
> Ok, will refrain from looking at it for now since it's a draft (didn't notice at first).

It's ready for review now.

2024-01-07 15:16 UTC, nurupo approved these changes

2024-01-07 15:17 UTC, merged