cleanup: Check that WINXP macro exists before comparing it.
TokTok/c-toxcore pull request #2655
Opened 2024-02-08 00:52 UTC by iphydf

Otherwise warnings happen.

2024-02-08 01:01 UTC, nurupo requested changes

2024-02-08 01:01 UTC, nurupo commented on toxcore/network.c
>  #endif /* defined(_WIN32) && defined(_WIN32_WINNT) && _WIN32_WINNT >= _WIN32_WINNT_WINXP */
The comment out of sync

2024-02-08 22:53 UTC, iphydf commented on toxcore/network.c
>  #endif /* defined(_WIN32) && defined(_WIN32_WINNT) && _WIN32_WINNT >= _WIN32_WINNT_WINXP */
Done.

2024-02-08 23:02 UTC, robinlinden approved these changes

2024-02-09 00:25 UTC, nurupo approved these changes

2024-02-09 00:26 UTC, merged